PRICES = {
    # table
    'page_title': {'type': 'css', 'locator': 'h1.versatile-header__title'},
    'start_date_title': {'type': 'css', 'locator': '[data-test="column-header-startDate"]'},
    'start_date_cell': {'type': 'css', 'locator': '[data-test="pricing-start-date"]'},
    'end_date_title': {'type': 'css', 'locator': '[data-test="column-header-endDate"]'},
    'end_date_cell': {'type': 'css', 'locator': '[data-test="pricing-end-date"]'},
    'price_list_title': {'type': 'css', 'locator': '[data-test="column-header-priceList"]'},
    'price_list_cell': {'type': 'css', 'locator': '[data-test="pricing-price-list"]'},
    'code_title': {'type': 'css', 'locator': '[data-test="column-header-code"]'},
    'code_cell': {'type': 'css', 'locator': '[data-test="pricing-code"]'},
    'nomenclature_title': {'type': 'css', 'locator': '[data-test="column-header-nomenclature"]'},
    'nomenclature_cell': {'type': 'css', 'locator': '[data-test="pricing-nomenclature"]'},
    'price_title': {'type': 'css', 'locator': '[data-test="column-header-price"]'},
    'price_cell': {'type': 'css', 'locator': '[data-test="pricing-price"]'},
    'promo_title': {'type': 'css', 'locator': '[data-test="column-header-promo"]'},
    'promo_cell': {'type': 'css', 'locator': '[data-test="column-header-promo"]'},
    'cause_title': {'type': 'css', 'locator': '[data-test="column-header-cause"]'},
    'cause_cell': {'type': 'css', 'locator': '[data-test="pricing-cause"]'},
    'icon_title': {'type': 'css', 'locator': '[data-test="column-header-icon"]'},
    'icon_cell': {'type': 'css', 'locator': '[data-test="pricing-status"]'},
    'export_btn': {'type': 'css', 'locator': '[data-test="pricing-status"]'},
    'first_row': {'type': 'css', 'locator': '.flex-table__body > div > div > :nth-child(1) a[role=button]'},

    # sidepanel
    'previous_price_title': {'type': 'css', 'locator': 'div.text-additional h5'},
    'current_price_title': {'type': 'css', 'locator': 'h5.text-additional'},
    'price_value': {'type': 'css', 'locator': '.side-panel__head div:nth-child(3) p'},
    'info_tab': {'type': 'css', 'locator': '.side-panel__head .tab:nth-of-type(1)'},
    'stages_tab': {'type': 'css', 'locator': '.side-panel__head .tab:nth-of-type(2)'},
    'status_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(1) h5'},
    'status_value': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(1) .side-panel-info-item__value'},
    'start_date_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(2) h5'},
    'start_date_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(2) div'},
    'end_date_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(3) h5'},
    'end_date_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(3) div'},
    'creating_date_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(4) h5'},
    'creating_date_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(4) div'},
    'price_list_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(5) h5'},
    'price_list_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(5) div'},
    'category_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(6) h5'},
    'category_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(5) div'},
    'code_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(7) h5'},
    'code_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(7) div'},
    'analogue_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(8) h5'},
    'analogue_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(8) div'},
    'vtm_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(9) h5'},
    'vtm_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(9) div'},
    'locality_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(10) h5'},
    'locality_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(10) div'},
    'promo_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(11) h5'},
    'promo_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(11) div'},
    'reason_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(12) h5'},
    'reason_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(12) div'},
    'comment_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(13) h5'},
    'comment_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(13) div'},
    'go_to_rule_btn': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(9) div'},
}
