ASSORTMENT = {
    # monitoring_section
    'date_monitoring_title': {'type': 'css', 'locator': 'div[data-test="column-header-dateMonitoring"]'},
    'region_title': {'type': 'css', 'locator': 'div[data-test="column-header-region"]'},
    'locality_title': {'type': 'css', 'locator': 'div[data-test="column-header-locality"]'},
    'analogue_code_title': {'type': 'css', 'locator': 'div[data-test="column-header-analogueСode"]'},
    'analogue_Code_title': {'type': 'css', 'locator': 'div[data-test="column-header-analogueCode"]'},
    'table': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper'},
    'analogue_title': {'type': 'css', 'locator': 'div[data-test="column-header-analogue"]'},
    'competitor_title': {'type': 'css', 'locator': 'div[data-test="column-header-competitor"]'},
    'price_title': {'type': 'css', 'locator': 'div[data-test="column-header-price"]'},
    'promotion_title': {'type': 'css', 'locator': 'div[data-test="column-header-promotion"]'},
    'first_row': {'type': 'xpath', 'locator': '(//a[contains(@data-test, "item-id")])[1]'},
    'date_monitoring_cell': {'type': 'css', 'locator': 'span[data-test="item-date-monitoring"]'},
    'monitoring_region_cell': {'type': 'css', 'locator': 'span[data-test="item-region"]'},
    'locality_cell': {'type': 'css', 'locator': 'span[data-test="item-locality"]'},
    'analogue_code_cell': {'type': 'xpath', 'locator': '(//span[@data-test="item-analogue-code"])[1]'},
    'analogue_cell': {'type': 'xpath', 'locator': '(//span[@data-test="item-analogue"])[1]'},
    'analogs_cells': {'type': 'css', 'locator': '[data-test="item-analogue"]'},
    'competitor_cell': {'type': 'xpath', 'locator': '(//span[@data-test="item-competitor"])[1]'},
    'price_cell': {'type': 'xpath', 'locator': '(//span[@data-test="item-price"])[1]'},
    'price_cells': {'type': 'css', 'locator': '[data-test="item-price"]'},
    'sceleton': {'type': 'css', 'locator': '.flex-table--loading:not(.flex-table--skeleton)'},
    'promotion_cell': {'type': 'xpath', 'locator': '(//span[@data-test="item-promotion"])[1]'},
    'row_count': {'type': 'css', 'locator': '.versatile-header__filter-postfix'},
    'monitoring_date_inp': {'type': 'css', 'locator': 'div[data-test="dateMonitoring"] input'},
    'monitoring_date_label': {'type': 'css', 'locator': 'div[data-test="dateMonitoring"] label'},
    'competitor_id_inp': {'type': 'css', 'locator': 'div[data-test="competitorRelationshipId"] input'},
    'competitor_id_label': {'type': 'css', 'locator': 'div[data-test="competitorRelationshipId"] label'},
    'store_guid_inp': {'type': 'css', 'locator': 'div[data-test="storeGuid"] input'},
    'store_guid_label': {'type': 'css', 'locator': 'div[data-test="storeGuid"] label'},
    'monitoring_region_inp': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(4) input'},
    'monitoring_region_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(4) label'},
    'locality_inp': {'type': 'css', 'locator': 'div[data-test="locality"] input'},
    'locality_label': {'type': 'css', 'locator': 'div[data-test="locality"] label'},
    'monitoring_analogue_inp': {'type': 'css', 'locator': 'div[data-test="analogue"] input'},
    'monitoring_analogue_label': {'type': 'css', 'locator': 'div[data-test="analogue"] label'},
    'competitor_inp': {'type': 'css', 'locator': 'div[data-test="competitor"] input'},
    'competitor_label': {'type': 'css', 'locator': 'div[data-test="competitor"] label'},
    'monitoring_analogue_code_inp': {'type': 'css', 'locator': 'div[data-test="analogueCode"] input'},
    'monitoring_analogue_code_label': {'type': 'css', 'locator': 'div[data-test="analogueCode"] label'},
    'monitoring_price_inp': {'type': 'css', 'locator': 'div[data-test="price"] input'},
    'monitoring_price_label': {'type': 'css', 'locator': 'div[data-test="price"] label'},
    'promotion_inp': {'type': 'css', 'locator': 'div[data-test="promotion"] input'},
    'promotion_label': {'type': 'css', 'locator': 'div[data-test="promotion"] label'},


    # mrc_section
    'mrc_title': {'type': 'css', 'locator': 'div[data-test="column-header-mrc"]'},
    'mrc_cell': {'type': 'css', 'locator': 'a[data-test="item-id-0"] span[data-test="item-mrc"]'},
    'start_date_title': {'type': 'css', 'locator': 'div[data-test="column-header-startDate"]'},
    'start_date_cell': {'type': 'css', 'locator': 'a[data-test="item-id-0"] span[data-test="item-start-date"]'},
    'end_date_title': {'type': 'css', 'locator': 'div[data-test="column-header-endDate"]'},
    'end_date_cell': {'type': 'css', 'locator': 'a[data-test="item-id-0"] span[data-test="item-end-date"]'},
    'sidepanel_mrc_inp': {'type': 'css', 'locator': 'div[data-test="mrc"] input'},
    'sidepanel_mrc_label': {'type': 'css', 'locator': 'div[data-test="mrc"] label'},
    'sidepanel_start_date_inp': {'type': 'css', 'locator': 'div[data-test="startDate"] input'},
    'sidepanel_start_date_label': {'type': 'css', 'locator': 'div[data-test="startDate"] label'},
    'sidepanel_end_date_inp': {'type': 'css', 'locator': 'div[data-test="endDate"] input'},
    'sidepanel_end_date_label': {'type': 'css', 'locator': 'div[data-test="endDate"] label'},
    'sidepanel_title': {'type': 'css', 'locator': 'div[data-test="endDate"] label'},
    'download_btn': {'type': 'css', 'locator': '.versatile-header__actions button'},


    # mcp_section
    'mcp_title': {'type': 'css', 'locator': 'div[data-test="column-header-msp"]'},
    'mcp_cell': {'type': 'css', 'locator': 'a[data-test="item-id-0"] span[data-test="item-msp"]'},
    'analogue_name': {'type': 'css', 'locator': '.vue-recycle-scroller__item-view div:nth-child(2) span'},
    'msp_price': {'type': 'css', 'locator': '.vue-recycle-scroller__item-view div:nth-child(3) span'},
    'nav_breads': {'type': 'css', 'locator': 'nav.versatile-header__breads'},
    'breads_1st_lvl': {'type': 'css', 'locator': 'ol > li:nth-child(1) a'},
    'mcp_download_btn': {'type': 'css', 'locator': '.versatile-header__actions button'},
    'analogue_code_inp': {'type': 'css', 'locator': '#input_5'},
    'analogue_code_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(1) label'},
    'analogue_name_inp': {'type': 'css', 'locator': '#input_6'},
    'analogue_name_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(2) label'},
    'value_inp': {'type': 'css', 'locator': '#input_7'},
    'mrc_value_inp': {'type': 'css', 'locator': '[data-test="minPrice"] input'},
    'mrc_value_label': {'type': 'css', 'locator': '[data-test="minPrice"] label'},
    'value_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(3) label'},
    'start_date_inp': {'type': 'css', 'locator': '#input_8'},
    'start_date_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(4) label'},
    'end_date_inp': {'type': 'css', 'locator': '#input_9'},
    'end_date_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(5) label'},


    # margin_limit_section
    'nomenclature_title': {'type': 'css', 'locator': 'div[data-test="column-header-nomenclature"]'},
    'nomenclature_cell': {'type': 'css', 'locator': '[data-test="margin-limit-nomenclature"]'},
    'second_nomenclature_cell': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(2) a '
                                                           '[data-test="margin-limit-nomenclature"]'},
    'third_nomenclature_cell': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(3) a '
                                                          '[data-test="margin-limit-nomenclature"]'},
    'assortment_type_title': {'type': 'css', 'locator': 'div[data-test="column-header-assortmentType"]'},
    'ml_assortment_type_cell': {'type': 'css', 'locator': '[data-test="margin-limit-assortment-type"]'},
    'value_title': {'type': 'css', 'locator': 'div[data-test="column-header-value"]'},
    'value_cell': {'type': 'css', 'locator': 'div[data-test="margin-limit-value"]'},
    'priority_title': {'type': 'css', 'locator': 'div[data-test="column-header-priority"]'},
    'priority_cell': {'type': 'css', 'locator': 'div[data-test="margin-limit-priority"]'},
    'vtm_title': {'type': 'css', 'locator': 'div[data-test="column-header-vtm"]'},
    'vtm_cell': {'type': 'css', 'locator': '[data-test="margin-limit-vtm"]'},
    'import_title': {'type': 'css', 'locator': 'div[data-test="column-header-import"]'},
    'import_cell': {'type': 'css', 'locator': '[data-test="margin-limit-import"]'},
    'brand_title': {'type': 'css', 'locator': 'div[data-test="column-header-brand"]'},
    'brand_cell': {'type': 'css', 'locator': '[data-test="margin-limit-brand"]'},
    'updated_by_title': {'type': 'css', 'locator': 'div[data-test="column-header-updatedBy"]'},
    'updated_by_cell': {'type': 'css', 'locator': 'a[data-test="item-id-0"] span[data-test="margin-limit-updated-by"]'},
    'updated_title': {'type': 'css', 'locator': 'div[data-test="column-header-updated"]'},
    'updated_cell': {'type': 'css', 'locator': 'a[data-test="item-id-0"] span[data-test="margin-limit-updated"]'},
    'check_all_checkbox': {'type': 'css', 'locator': 'input[data-test="check-all-items"]'},
    'check_first_item_checkbox': {'type': 'xpath', 'locator': '(//input[@data-test="check-item"])[1]'},
    'add_margin_limit_btn': {'type': 'css', 'locator': 'button[data-test="create-margin-limit"]'},
    'upload_margin_limit_btn': {'type': 'css', 'locator': 'button[data-test="upload-margin-limits"]'},
    'download_margin_limit_btn': {'type': 'css', 'locator': 'button[data-test="download-margin-limits"]'},
    'no_data': {'type': 'css', 'locator': '.no-data'},
    'no_data_description': {'type': 'css', 'locator': '.no-data__text'},
    # adding margin limit description
    'nomenclature_step_num': {'type': 'css', 'locator': 'div[data-test="step:nomenclature"] div'},
    'nomenclature_tab': {'type': 'css', 'locator': 'div[data-test="step:nomenclature"]'},
    'loader_spinner': {'type': 'css', 'locator': '.loader__spinner'},
    'nomenclature_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(1) > div'},
    'first_nomenclature_label': {'type': 'css', 'locator': '[data-test="treeview-selection-item"]:nth-of-type(1) '
                                                           '.radio__label'},
    'nomenclature_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(1) > h5'},
    'nomenclature_step_name': {'type': 'css', 'locator': 'div[data-test="step:nomenclature"] p'},
    'options_step_num': {'type': 'css', 'locator': 'div[data-test="step:extraOptions"] div'},
    'options_tab': {'type': 'css', 'locator': 'div[data-test="step:extraOptions"]'},
    'options_step_name': {'type': 'css', 'locator': 'div[data-test="step:extraOptions"] p'},
    'checkbox_search_inp': {'type': 'css', 'locator': 'div[data-test="treeview-checkbox-search"] input'},
    'sidepanel_search_inp': {'type': 'css', 'locator': '[data-test="treeview-selection-search"] input'},
    'select_all_inp': {'type': 'css', 'locator': 'input[data-test="treeview-checkboxes-master-control"]'},
    'first_category_inp': {'type': 'xpath', 'locator': '(//div[@data-test="treeview-checkbox"]//input)[1]'},
    'category_with_subcategories': {'type': 'xpath', 'locator': '(//div[@data-test="treeview-checkbox" and not'
                                                                '(contains(@class, "no-children"))]//input)[1]'},
    'open_subcategories_btn': {'type': 'xpath', 'locator': '(//div[@data-test="treeview-checkbox" and not(contains'
                                                           '(@class, "no-children"))]/div/span)[1]'},
    'category_without_subcategories': {'type': 'xpath', 'locator': '(//div[@data-test="treeview-checkbox" and '
                                                                   'contains(@class, "no-children")]//input)[1]'},
    'back_to_main_breadcrumb': {'type': 'xpath', 'locator': '(//button[@data-test="treeview-checkbox-breadcrumbs-'
                                                            'item-base"])[1]'},
    'uncheck_all_btn': {'type': 'css', 'locator': 'button[data-test="uncheck-all"]'},
    'go_to_next_step_btn': {'type': 'css', 'locator': 'button[data-test="go-to-next-step"]'},
    'nomenclature_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(1) > div'},
    'assortment_type_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(2) > div'},
    'assortment_type_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(2) > h5'},
    'margin_limit_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(3) > div'},
    'margin_limit_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(3) > h5'},
    'assortment_type_btn': {'type': 'css', 'locator': 'div[data-test="select-assortment-type"] span'},
    'assortment_type_inp': {'type': 'css', 'locator': 'div[data-test="select-assortment-type"] input'},
    'first_menu_item': {'type': 'xpath', 'locator': '(//div[@class="search-filter__menu-item"])[1]'},
    'second_menu_item': {'type': 'xpath', 'locator': '(//div[@class="search-filter__menu-item"])[2]'},
    'third_menu_item': {'type': 'xpath', 'locator': '(//div[@class="search-filter__menu-item"])[3]'},
    'vtm_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(4) > div'},
    'vtm_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(4) > h5'},
    'is_import_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(5) > div'},
    'is_import': {'type': 'css', 'locator': '.side-panel__content p'},
    'is_import_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(5) > h5'},
    'vtm_btn': {'type': 'css', 'locator': 'div[data-test="select-vtm"] span'},
    'vtm_inp': {'type': 'css', 'locator': 'div[data-test="select-vtm"] input'},
    'is_import_unknown': {'type': 'css', 'locator': '.side-panel__content .radio:nth-of-type(1) .radio__label'},
    'is_import_yes': {'type': 'css', 'locator': '.side-panel__content .radio:nth-of-type(2) .radio__label'},
    'is_import_no': {'type': 'css', 'locator': '.side-panel__content .radio:nth-of-type(3) .radio__label'},
    'brand_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(6) > div'},
    'priority_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(7) > div'},
    'rule_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(8) > div'},
    'brand_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(6) > h5'},
    'brand_btn': {'type': 'css', 'locator': 'div[data-test="select-brand"] span'},
    'brand_inp': {'type': 'css', 'locator': 'div[data-test="select-brand"] input'},
    'limit_inp': {'type': 'css', 'locator': 'div[data-test=enter-limit] input'},
    'limit_inp_error': {'type': 'css', 'locator': '[data-test="enter-limit"] .input_error-annotation'},
    'limit_label': {'type': 'css', 'locator': 'div[data-test=enter-limit] label'},
    'priority_inp': {'type': 'css', 'locator': 'div[data-test="select-priority"] input'},
    'priority_inp_error': {'type': 'css', 'locator': '[data-test=select-priority] .input_error-annotation'},
    'priority_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(7) > h5'},
    'priority_btn': {'type': 'css', 'locator': 'div[data-test=select-priority] span'},
    'high_priority': {'type': 'css', 'locator': '.menu [data-index="0"]'},
    'average_priority': {'type': 'css', 'locator': '.menu [data-index="1"]'},
    'low_priority': {'type': 'css', 'locator': '.menu [data-index="2"]'},
    'rule_inp': {'type': 'css', 'locator': 'div[data-test=select-rule] input'},
    'rule_inp_error': {'type': 'css', 'locator': '[data-test=select-rule] .input_error-annotation'},
    'rule_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(8) > h5'},
    'rule_btn': {'type': 'css', 'locator': 'div[data-test=select-rule] span'},
    'first_price_rule': {'type': 'css', 'locator': '.menu [data-index="0"]'},
    'kvi_rule': {'type': 'css', 'locator': '.menu [data-index="1"]'},
    'go_to_previous_step_btn': {'type': 'css', 'locator': 'button[data-test="go-to-prev-step"]'},
    'submit_btn': {'type': 'css', 'locator': 'button[data-test="submit"]'},
    'edit_btn': {'type': 'css', 'locator': '[data-test="start-editing"]'},
    'editing_nomenclature_inp': {'type': 'css', 'locator': '[data-test="select-nomenclature"] input'},
    'edit_ml_value_inp': {'type': 'css', 'locator': '[data-test="edit-margin-limit-value"] input'},
    'second_nomenclature': {'type': 'css', 'locator': '[data-test="treeview-selection-item"]:nth-of-type(2) '
                                                      '.radio__label'},
    'apply_btn': {'type': 'css', 'locator': '[data-test="apply"]'},
    'unselect_btn': {'type': 'css', 'locator': '[data-test="unselectAll"]'},
    'assortment_type_checkbox': {'type': 'css', 'locator': '[data-index="0"] .checkbox__control'},
    'vtm_menu_item': {'type': 'css', 'locator': '[data-index="0"]>div>div'},
    'brand_menu_item': {'type': 'css', 'locator': '[data-index="0"]>div>div'},
    'priority_menu_item': {'type': 'css', 'locator': '[data-index="1"]>div>div'},
    'rule_menu_item': {'type': 'css', 'locator': '[data-index="0"]>div>div'},
    'save_changes_btn': {'type': 'css', 'locator': '[data-test="save-changes"]'},
    'cancel_changes_btn': {'type': 'css', 'locator': '[data-test="cancel"]'},
    'nomenclature_error': {'type': 'css', 'locator': '[data-test="select-nomenclature"] .input_error-annotation'},
    'value_error': {'type': 'css', 'locator': '[data-test="edit-margin-limit-value"] .input_error-annotation'},


    # price_limit_section
    'category_title': {'type': 'css', 'locator': 'div[data-test="column-header-category"]'},
    'category_cell': {'type': 'css', 'locator': 'a[data-test="item-id-0"] span[data-test="price-limit-category"]'},
    'group_title': {'type': 'css', 'locator': 'div[data-test="column-header-group"]'},
    'group_cell': {'type': 'css', 'locator': 'a[data-test="item-id-0"] span[data-test="price-limit-group"]'},
    'subgroup_title': {'type': 'css', 'locator': 'div[data-test="column-header-subgroup"]'},
    'subgroup_cell': {'type': 'css', 'locator': 'a[data-test="item-id-0"] span[data-test="price-limit-subgroup"]'},
    'pl_analogue_code_cell': {'type': 'css',
                              'locator': 'a[data-test="item-id-0"] span[data-test="price-limit-analogue-code"]'},
    'pl_analogue_cell': {'type': 'css', 'locator': 'a[data-test="item-id-0"] span[data-test="price-limit-analogue"]'},
    'pl_assortment_type_cell': {'type': 'css',
                                'locator': 'a[data-test="item-id-0"] div[data-test="price-limit-assortment-type"]'},
    'min_price_title': {'type': 'css', 'locator': 'div[data-test="column-header-minPrice"]'},
    'min_price_cell': {'type': 'css', 'locator': 'a[data-test="item-id-0"] div[data-test="price-limit-min-price"]'},
    'max_price_title': {'type': 'css', 'locator': 'div[data-test="column-header-maxPrice"]'},
    'max_price_cell': {'type': 'css', 'locator': 'a[data-test="item-id-0"] div[data-test="price-limit-max-price"]'},
    'author_title': {'type': 'css', 'locator': 'div[data-test="column-header-authorOfChanges"]'},
    'author_cell': {'type': 'css', 'locator': 'a[data-test="item-id-0"] span[data-test="price-limit-author-of-changes"]'},
    'date_title': {'type': 'css', 'locator': 'div[data-test="column-header-dateOfChanges"]'},
    'date_cell': {'type': 'css', 'locator': 'a[data-test="item-id-0"] span[data-test="price-limit-date-of-changes"]'},
    'category_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(1) > div'},
    'category_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(1) > h5'},
    'group_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(2) > div'},
    'group_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(2) > h5'},
    'subgroup_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(3) > div'},
    'subgroup_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(3) > h5'},
    'pl_analogue_code_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(4) > div'},
    'pl_analogue_code_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(4) > h5'},
    'pl_analogue_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(5) > div'},
    'pl_analogue_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(5) > h5'},
    'pl_assortment_type_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(6) > div'},
    'pl_assortment_type_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(6) '
                                                           '> h5'},
    'pl_min_price_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(7) > div'},
    'pl_min_price_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(7) > h5'},
    'pl_max_price_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(8) > div'},
    'pl_max_price_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(8) > h5'},


    # complex_discounts_section
    'cd_analogue_code_cell': {'type': 'xpath', 'locator': '(//span[@data-test="item-analogueCode"])[1]'},
    'department_code_title': {'type': 'css', 'locator': '[data-test="column-header-departmentCode"]'},
    'department_title': {'type': 'css', 'locator': '[data-test="column-header-department"]'},
    'cd_department_code_cell': {'type': 'xpath', 'locator': '(//span[@data-test="item-departmentCode"])[1]'},
    'cd_department_title': {'type': 'css', 'locator': 'div[data-test="item-department"]'},
    'cd_department_cell': {'type': 'xpath', 'locator': '(//span[@data-test="item-department"])[1]'},
    'subdivision_id_inp': {'type': 'xpath', 'locator': '[data-test="subdivisionId"] input'},
    'subdivision_id_label': {'type': 'xpath', 'locator': '[data-test="subdivisionId"] label'},
    'subdivision_name_inp': {'type': 'xpath', 'locator': '[data-test="subdivisionName"] input'},
    'subdivision_name_label': {'type': 'xpath', 'locator': '[data-test="subdivisionName"] label'},
    'from_date_inp': {'type': 'css', 'locator': '[data-test="fromDate"] input'},
    'from_date_label': {'type': 'css', 'locator': '[data-test="fromDate"] label'},
    'mcp_inp': {'type': 'css', 'locator': '[data-test="min-price"] input'},
    'mcp_label': {'type': 'css', 'locator': '[data-test="min-price"] label'},
    'to_date_inp': {'type': 'css', 'locator': '[data-test="toDate"] input'},
    'to_date_textarea': {'type': 'css', 'locator': '[data-test="toDate"] textarea'},
    'to_date_label': {'type': 'css', 'locator': '[data-test="toDate"] label'},


    # production_countries_section
    'counties_title': {'type': 'css', 'locator': 'div[data-test="column-header-country"]'},
    'counties_cell': {'type': 'xpath', 'locator': '(//span[@data-test="item-country"])[1]'},
    'countries_has_import_title': {'type': 'css', 'locator': 'div[data-test="column-header-hasImport"]'},
    'countries_has_import_cell': {'type': 'xpath', 'locator': '(//span[@data-test="item-has-import"])[1]'},
    'counties_author_title': {'type': 'css', 'locator': 'div[data-test="column-header-author"]'},
    'counties_author_cell': {'type': 'xpath', 'locator': '(//span[@data-test="item-author"])[1]'},
    'counties_date_title': {'type': 'css', 'locator': 'div[data-test="column-header-changesDate"]'},
    'counties_date_cell': {'type': 'xpath', 'locator': '(//span[@data-test="item-changes-date"])[1]'},
    'country_name_inp': {'type': 'xpath', 'locator': '[data-test="countryName"] input'},
    'country_name_label': {'type': 'xpath', 'locator': '[data-test="countryName"] label'},
    'import_inp': {'type': 'xpath', 'locator': '[data-test="import"] input'},
    'import_label': {'type': 'xpath', 'locator': '[data-test="import"] label'},

    # supply_type_section
    'supply_type_title': {'type': 'css', 'locator': 'div[data-test="column-header-type"]'},
    'supply_type_cell': {'type': 'xpath', 'locator': '(//span[@data-test="item-type"])[1]'},
    'region_inp': {'type': 'xpath', 'locator': '[data-test="region"] input'},
    'region_label': {'type': 'xpath', 'locator': '[data-test="region"] label'},
    'st_analogue_code_inp': {'type': 'xpath', 'locator': '[data-test="analogueCode"] input'},
    'st_analogue_code_label': {'type': 'xpath', 'locator': '[data-test="analogueCode"] label'},
    'analogue_inp': {'type': 'xpath', 'locator': '[data-test="analogue"] input'},
    'analogue_label': {'type': 'xpath', 'locator': '[data-test="analogue"] label'},
    'department_id_inp': {'type': 'xpath', 'locator': '[data-test="departmentId"] input'},
    'department_id_label': {'type': 'xpath', 'locator': '[data-test="departmentId"] label'},
    'type_inp': {'type': 'xpath', 'locator': '[data-test="type"] input'},
    'type_label': {'type': 'xpath', 'locator': '[data-test="type"] label'},


    # assortment_type_section
    'name_title': {'type': 'css', 'locator': 'div[data-test="column-header-name"]'},
    'at_name_cell': {'type': 'xpath', 'locator': '(//span[@data-test="assortment-type-item-name"])[1]'},
    'at_category_cell': {'type': 'xpath', 'locator': '(//span[@data-test="assortment-type-item-category"])[1]'},
    'at_analogue_code_cell': {'type': 'xpath',
                              'locator': '(//div[@data-test="assortment-type-item-analogue-code"]/div)[1]'},
    'at_analogue_cell': {'type': 'xpath', 'locator': '(//span[@data-test="assortment-type-item-analogue"])[1]'},
    'at_kind_title': {'type': 'css', 'locator': 'div[data-test="column-header-kind"]'},
    'at_kind_cell': {'type': 'xpath', 'locator': '(//span[@data-test="assortment-type-item-kind"])[1]'},
    'at_oracle_upload_title': {'type': 'css', 'locator': 'div[data-test="column-header-uploadDateToOracle"]'},
    'at_oracle_upload_cell': {'type': 'xpath',
                              'locator': '(//span[@data-test="assortment-type-item-upload-date-to-oracle"])[1]'},
    'at_assortment_type_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(1) > div'},
    'at_assortment_type_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(1)'
                                                           ' > h5'},
    'at_category_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(2) > div'},
    'at_category_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(2) > h5'},
    'at_analogue_code_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(3) > div'},
    'at_analogue_code_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(3) > h5'},
    'at_analogue_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(4) > div'},
    'at_analogue_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(4) > h5'},
    'kind_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(5) > div'},
    'kind_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(5) > h5'},
    'oracle_upload_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(6) > div'},
    'oracle_upload_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(6) > h5'},
    'assortment_types_label': {'type': 'css', 'locator': '.assortment-type-side-panel__type-block-caption'},
    'assortment_types_list': {'type': 'css', 'locator': '.assortment-type-side-panel__type-block-list'},


    # goods_section
    'product_category_cell': {'type': 'xpath', 'locator': '(//span[@data-test="product-category"])[1]'},
    'product_group_cell': {'type': 'xpath', 'locator': '(//span[@data-test="product-group"])[1]'},
    'product_subgroup_cell': {'type': 'xpath', 'locator': '(//span[@data-test="product-subgroup"])[1]'},
    'product_analogue_code_cell': {'type': 'xpath', 'locator': '(//span[@data-test="product-analogue-code"])[1]'},
    'product_analogue_cell': {'type': 'xpath', 'locator': '(//span[@data-test="product-analogue"])[1]'},
    'product_assortment_type_cell': {'type': 'xpath', 'locator': '(//span[@data-test="product-assortment-type"])[1]'},
    'product_import_cell': {'type': 'xpath', 'locator': '(//div[@data-test="product-import"]/div)[1]'},
    'product_kind_cell': {'type': 'xpath', 'locator': '(//span[@data-test="product-kind"])[1]'},
    'product_category_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(1) h5'},
    'product_category_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(1) div'},
    'product_group_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(2) h5'},
    'product_group_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(2) div'},
    'product_subgroup_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(3) h5'},
    'product_subgroup_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(3) div'},
    'product_analogue_code_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(4) h5'},
    'product_analogue_code_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(4) div'},
    'product_analogue_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(5) h5'},
    'product_analogue_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(5) div'},
    'product_assortment_type_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(6) h5'},
    'product_assortment_type_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(6) div'},
    'product_mrc_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(7) > div:nth-child(1) h5'},
    'product_mrc_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(7) > div:nth-child(1) div'},
    'product_mcp_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(7) > div:nth-child(2) h5'},
    'product_mcp_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(7) > div:nth-child(2) div'},
    'product_volume_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(8) > div:nth-child(1) h5'},
    'product_volume_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(8) > div:nth-child(1) div'},
    'product_weight_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(8) > div:nth-child(2) h5'},
    'product_weight_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(8) > div:nth-child(2) div'},
    'product_brand_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(9) > div:nth-child(1) h5'},
    'product_brand_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(9) > div:nth-child(1) div'},
    'product_country_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(9) > div:nth-child(2) h5'},
    'product_country_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(9) > div:nth-child(2) div'},
    'product_type_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(10) > div:nth-child(1) h5'},
    'product_type_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(10) > div:nth-child(1) div'},
    'product_vtm_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(10) > div:nth-child(2) h5'},
    'product_vtm_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(10) > div:nth-child(2) div'},
    'product_import_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(11) h5'},
    'product_import_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(11) div'},
    'product_kind_label': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(12) h5'},
    'product_kind_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(12) div'},
}
