FILTER = {
    'search_inp': {'type': 'css', 'locator': 'input.input--search'},
    'filter_search_inp': {'type': 'css', 'locator': '.filter-body input.input--search'},
    'open_filter_btn': {'type': 'css', 'locator': 'div[data-test="changeDropDown"]'},
    'open_filter_tooltip': {'type': 'xpath', 'locator': '//div[@data-test="changeDropDown"]/../div[2]'},
    'filter_tooltip': {'type': 'xpath', 'locator': '(//div[@data-test="changeDropDown"]/../div[2])[1]'},
    'price_filter_btn': {'type': 'css', 'locator': 'div.filter-body div[role=button]:nth-child(1)'},
    'period_filter_btn': {'type': 'css', 'locator': 'div.filter-body div[role=button]:nth-child(2)'},
    'category_filter_btn': {'type': 'css', 'locator': 'div.filter-body div[role=button]:nth-child(3)'},
    'application_area_btn': {'type': 'css', 'locator': 'div.filter-body div[role=button]:nth-child(4)'},
    'loc_btn': {'type': 'css', 'locator': 'div.filter-body div[role=button]:nth-child(5)'},
    'rc_btn': {'type': 'css', 'locator': 'div.filter-body div[role=button]:nth-child(6)'},
    'author_btn': {'type': 'css', 'locator': 'div.filter-body div[role=button]:nth-child(7)'},
    'updates_btn': {'type': 'css', 'locator': 'div.filter-body div[role=button]:nth-child(8)'},
    'filter_wrap': {'type': 'css', 'locator': 'div.filter-wrap'},
    'filter_wrap_header': {'type': 'css', 'locator': 'div.filter-wrap h5'},
    'open_calendar_btn': {'type': 'css', 'locator': 'span[data-test="clickAfterIcon"]'},
    'calendar': {'type': 'css', 'locator': 'div.datepicker__menu'},
    'date_checkbox': {'type': 'css', 'locator': 'input[data-test="endDateInfinity"]'},
    'date_month_btn': {'type': 'css', 'locator': 'div.dp__month_year_select:nth-child(1)'},
    'date_year_btn': {'type': 'css', 'locator': 'div.dp__month_year_select:nth-child(2)'},
    'previous_year_btn': {'type': 'css', 'locator': '[data-test="2022"]'},
    'next_year_btn': {'type': 'css', 'locator': '[data-test="2024"]'},
    'next_month_btn': {'type': 'css', 'locator': 'div[aria-label="Next month"]'},
    'previous_month_btn': {'type': 'css', 'locator': 'div[aria-label="Previous month"]'},
    'close_filter_btn': {'type': 'css', 'locator': 'span[data-test="toggleModal"]'},
    'clear_filter_btn': {'type': 'css', 'locator': 'button[data-test="clearFilter"]'},
    'apply_filter_btn': {'type': 'css', 'locator': 'button[data-test="applyFilter"]'},
    'selected_parameters_counter': {'type': 'css', 'locator': 'span.text-black'},
    'selected_parameters_text': {'type': 'xpath', 'locator': '//span[@class="text-black"]/..'},
    'price_from_inp': {'type': 'css', 'locator': ' input[placeholder="От, ₽"]'},
    'price_to_inp': {'type': 'css', 'locator': 'input[placeholder="До, ₽"]'},
    'period_inp': {'type': 'css', 'locator': 'input[placeholder="дд.мм.гггг — дд.мм.гггг"]'},
    'period_label': {'type': 'css', 'locator': '[data-test="datepicker-input"] label'},
    'items_counter': {'type': 'xpath', 'locator': 'div.versatile-header__filter-postfix'},
    'no_data': {'type': 'css', 'locator': '.no-data'},
    'no_data_text': {'type': 'css', 'locator': '.no-data__text'},
    'circle_icon': {'type': 'css', 'locator': '[data-test="changeDropDown"] > span:nth-child(2)'},
    'first_tab': {'type': 'css', 'locator': '.filter-wrap .tab:nth-of-type(1)'},
    'second_tab': {'type': 'css', 'locator': '.filter-wrap .tab:nth-of-type(2)'},
    'autor': {'type': 'css', 'locator': '[data-test="category:author"]'},
    'download_date': {'type': 'css', 'locator': '[data-test="category:download_date"]'},
    'changed_prices': {'type': 'css', 'locator': '[data-test="category:changed_prices"]'},
    'price': {'type': 'css', 'locator': '[data-test="category:price"]'},
    'begin_date': {'type': 'css', 'locator': '[data-test="category:begin_date"]'},
    'begin_date_error_icon': {'type': 'css', 'locator': '[data-test="category:begin_date"] .text-negative'},
    'end_date': {'type': 'css', 'locator': '[data-test="category:end_date"]'},
    'nomenclature': {'type': 'css', 'locator': '[data-test="category:nomenclature"]'},
    'analogue_code': {'type': 'css', 'locator': '[data-test="category:analogue_code"]'},
    'price_list': {'type': 'css', 'locator': '[data-test="category:price_list"]'},
    'region': {'type': 'css', 'locator': '[data-test="category:region"]'},
    'city': {'type': 'css', 'locator': '[data-test="category:city"]'},
    'analog': {'type': 'css', 'locator': '[data-test="category:analog"]'},
    'competitor': {'type': 'css', 'locator': '[data-test="category:competitor"]'},
    'promotion': {'type': 'css', 'locator': '[data-test="category:promotion"]'},
    'msp': {'type': 'css', 'locator': '[data-test="category:msp"]'},
    'from_date': {'type': 'css', 'locator': '[data-test="category:from_date"]'},
    'to_date': {'type': 'css', 'locator': '[data-test="category:to_date"]'},
    'mrp': {'type': 'css', 'locator': '[data-test="category:mrp"]'},
    'department': {'type': 'css', 'locator': '[data-test="category:department"]'},
    'updated_at': {'type': 'css', 'locator': '[data-test="category:updated_at"]'},
    'labels': {'type': 'css', 'locator': '.checkbox__label'},
    'reason': {'type': 'css', 'locator': '[data-test="category:reason"]'},
    'is_action': {'type': 'css', 'locator': '[data-test="category:is_action"]'},
    'is_import': {'type': 'css', 'locator': '[data-test="category:product_import"]'},
    'assortment_type': {'type': 'css', 'locator': '[data-test="category:assortment_type"]'},
    'brand_name': {'type': 'css', 'locator': '[data-test="category:brand_name"]'},
    'trade_mark_owner_name': {'type': 'css', 'locator': '[data-test="category:trade_mark_owner_name"]'},
    'chips_value': {'type': 'css', 'locator': 'div.chips > span:nth-child(1)'},
    'chips_delete_btn': {'type': 'css', 'locator': 'span[data-test="deleteChips"]'},
    'from_tooltip': {'type': 'css', 'locator': '.filter-body .flex-grow .vtooltip:nth-of-type(1) div.vtooltip__content'},
    'to_tooltip': {'type': 'css', 'locator': '.filter-body .flex-grow .vtooltip:nth-of-type(2) div.vtooltip__content'},
    'last_day': {'type': 'xpath', 'locator': '(//div[@class="day"])[last()]'},
    'first_day': {'type': 'xpath', 'locator': '(//div[@class="day"])[1]'},
    'clear_input_btn': {'type': 'css', 'locator': '[data-test="clearableInput"]'},
    'error_message': {'type': 'css', 'locator': '.input_error-annotation'},
    'empty_space': {'type': 'css', 'locator': '.flex-grow div.h-full'},
    'first_search_item': {'type': 'css', 'locator': '[data-index="0"] .checkbox__label'},
    'second_search_item': {'type': 'css', 'locator': '[data-index="1"] .checkbox__label'},
    'third_search_item': {'type': 'css', 'locator': '[data-index="2"] .checkbox__label'},
    'checkbox_label': {'type': 'css', 'locator': '.checkbox__label'},
    'check_all_txt': {'type': 'css', 'locator': '.search-filter__menu>:nth-child(1) .checkbox__label'},
    'check_all_btn': {'type': 'css', 'locator': '.search-filter__menu>:nth-child(1) .checkbox__control'},
    'first_day_btn': {'type': 'css', 'locator': '.dp__calendar_row:nth-of-type(1) .day'},
    'last_day_btn': {'type': 'xpath', 'locator': '(//div[@class="day"])[last()]'},
    'btn_loader': {'type': 'css', 'locator': '.btn__loader-wrap'},
    'sceleton': {'type': 'css', 'locator': '.flex-table--loading:not(.flex-table--skeleton)'},
}
