MENU = {
    'menu_aside': {'type': 'xpath', 'locator': '//aside'},
    'toggle_menu': {'type': 'css', 'locator': 'aside div[data-test="toggleMenu"]'},
    'main_page': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(1) > a'},
    'main_page_title': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(1) .side-bar__item-name span'},
    'all_prices': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(2) > a'},
    'all_prices_title': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(2) .side-bar__item-name span'},
    'price_calculating': {'type': 'css', 'locator': 'aside > div:nth-child(2) [data-test="closeMenu"]:nth-of-type(3) a'},
    'price_calculating_title': {'type': 'xpath',
                                'locator': '(//span[contains(@class, "side-bar__item-name")]/span)[3]'},
    'competitive_prices': {'type': 'xpath', 'locator': '(//div[@data-test="toggleAccordion"])[1]//li[1]/a'},
    'competitive_prices_title': {'type': 'xpath', 'locator': '(//div[@data-test="toggleAccordion"])[1]//li[1]/a/div'},
    'kib_prices_title': {'type': 'xpath', 'locator': '(//div[@data-test="toggleAccordion"])[1]//li[2]/a/div'},
    'shock_prices_title': {'type': 'xpath', 'locator': '(//div[@data-test="toggleAccordion"])[1]//li[3]/a/div'},
    'prices_setting': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(4) > a'},
    'prices_setting_title': {'type': 'css',
                             'locator': 'div[data-test="closeMenu"]:nth-child(4) .side-bar__item-name span'},
    'shelf_prices': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(5) > a'},
    'shelf_prices_title': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(5) .side-bar__item-name span'},
    'reporting': {'type': 'xpath', 'locator': '(//div[@data-test="openMenu"])[2]'},
    'retail_prices_urc': {'type': 'xpath', 'locator': '(//div[@data-test="toggleAccordion"])[2]//li[1]/a'},
    'retail_prices_urc_title': {'type': 'xpath', 'locator': '(//div[@data-test="toggleAccordion"])[2]//li[1]/a/div'},
    'kvi_report': {'type': 'xpath', 'locator': '(//div[@data-test="toggleAccordion"])[2]//li[2]/a'},
    'kvi_report_title': {'type': 'xpath', 'locator': '(//div[@data-test="toggleAccordion"])[2]//li[2]/a/div'},
    'kib_report': {'type': 'xpath', 'locator': '(//div[@data-test="toggleAccordion"])[2]//li[3]/a'},
    'kib_report_title': {'type': 'xpath', 'locator': '(//div[@data-test="toggleAccordion"])[2]//li[3]/a/div'},
    'reporting_title': {'type': 'xpath', 'locator': '(//span[contains(@class, "side-bar__item-name")]/span)[5]'},
    'rules_setup': {'type': 'css', 'locator': 'a[href="/rules_setup"]'},
    'rules_setup_title': {'type': 'css',
                          'locator': 'div[data-test="closeMenu"]:nth-child(7) .side-bar__item-name span'},
    'directories': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(7) > a'},
    'directories_tooltip': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(7) > div'},
    'directories_title': {'type': 'css',
                          'locator': 'div[data-test="closeMenu"]:nth-child(8) .side-bar__item-name span'},
    'price_lists': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(9) > a'},
    'price_lists_title': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(9) .side-bar__item-name span'},
    'tasks': {'type': 'css', 'locator': 'div[data-test="openMenu"]:nth-child(1) > a'},
    'tasks_title': {'type': 'css', 'locator': 'div[data-test="openMenu"]:nth-child(1) .side-bar__item-name span'},
    'users': {'type': 'css', 'locator': '[href="/users_control"].side-bar__item-wrap'},
    'users_title': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(10) .side-bar__item-name span'},
    'action_log': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(11) > a'},
    'action_log_title': {'type': 'css',
                         'locator': 'div[data-test="closeMenu"]:nth-child(12) .side-bar__item-name span'},
    'notifications': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(1) > button'},
    'profile': {'type': 'css', 'locator': 'div[data-test="closeMenu"]:nth-child(2) > button'},
    'profile_tooltip': {'type': 'css', 'locator': 'aside>div:last-child div:last-child .vtooltip__content'},
    'composite_price_index': {'type': 'xpath', 'locator': '(//div[@data-test="toggleAccordion"])[2]//li[4]/a'},
    'collapse_menu': {'type': 'css', 'locator': 'aside div[data-test="toggleMenu"] .side-bar__item-name'},
}
