PARAMETERS = {
    # sprice_section
    'open_context_menu_btn': {'type': 'xpath',
                              'locator': '//div[contains(@data-test, "card")]//div[@data-test="toggle"]'},
    'rename_btn': {'type': 'xpath', 'locator': '.visible .context-menu > div:nth-child(1)'},
    'create_copy_btn': {'type': 'xpath', 'locator': '.visible .context-menu > div:nth-child(2)'},
    'delete_btn': {'type': 'xpath', 'locator': '.visible .context-menu > div:nth-child(3)'},
    'add_subitem_btn': {'type': 'css', 'locator': 'button[data-test="add-subitem"]'},
    'add_subitem_description': {'type': 'css', 'locator': 'div.side-panel__content > div:nth-child(1)'},
    'subitem_name_inp': {'type': 'css', 'locator': 'div[data-test="name"] input'},
    'subitem_category_inp': {'type': 'css', 'locator': 'div[data-test="toggleShowMenu"] input'},
    'categories_search_inp': {'type': 'css', 'locator': 'div.menu div[data-test="search"] input'},
    'select_all_checkbox': {'type': 'css', 'locator': 'input[data-test="select-all"]'},
    'select_all_label': {'type': 'xpath', 'locator': '(//div[@class="menu"]//span[@class="checkbox__label"])[1]'},
    'select_first_category_checkbox': {'type': 'xpath', 'locator': '(//label[@class="checkbox"]/input)[2]'},
    'first_category_label': {'type': 'xpath', 'locator': '(//div[@class="menu"]//span[@class="checkbox__label"])[2]'},
    'sprice_tooltip': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(4)'},
    'end_at_title': {'type': 'css', 'locator': '.s-price-table__header > div:nth-child(1)'},
    'bit_depth_title': {'type': 'css', 'locator': '.s-price-table__header--main > div:nth-child(1)'},
    'row_0': {'type': 'css', 'locator': 'div[data-test="row:0"]'},
    'row_1': {'type': 'css', 'locator': 'div[data-test="row:1"]'},
    'row_2': {'type': 'css', 'locator': 'div[data-test="row:2"]'},
    'row_3': {'type': 'css', 'locator': 'div[data-test="row:3"]'},
    'row_4': {'type': 'css', 'locator': 'div[data-test="row:4"]'},
    'row_5': {'type': 'css', 'locator': 'div[data-test="row:5"]'},
    'row_6': {'type': 'css', 'locator': 'div[data-test="row:6"]'},
    'row_7': {'type': 'css', 'locator': 'div[data-test="row:7"]'},
    'row_8': {'type': 'css', 'locator': 'div[data-test="row:8"]'},
    'row_9': {'type': 'css', 'locator': 'div[data-test="row:9"]'},
    'bit_depth_1': {'type': 'xpath', 'locator': '//div[@class="s-price-table__header--main"]/div[2]/div[1]'},
    'bit_depth_10': {'type': 'xpath', 'locator': '//div[@class="s-price-table__header--main"]/div[2]/div[2]'},
    'bit_depth_100': {'type': 'xpath', 'locator': '//div[@class="s-price-table__header--main"]/div[2]/div[3]'},
    'bit_depth_1000': {'type': 'xpath', 'locator': '//div[@class="s-price-table__header--main"]/div[2]/div[4]'},
    'cancel_sprice_btn': {'type': 'css', 'locator': 'button[data-test="cancel"]'},
    'save_sprice_btn': {'type': 'css', 'locator': 'button[data-test="save"]'},
    'delete_sprice_btn': {'type': 'css', 'locator': 'button[data-test="delete"]'},
    'deleting_title': {'type': 'css', 'locator': '.modal-content h5'},
    'deleting_text': {'type': 'css', 'locator': '.modal-body div'},
    'sprice_card_title': {'type': 'xpath', 'locator': '(//div[contains(@data-test, "card")]/div/div/div)[1]'},
    'log_margin_btn': {'type': 'css', 'locator': 'label[data-test="isLaunched"] > input'},

    # exceptions_section
    'exception_card': {'type': 'xpath', 'locator': '//div[contains(@data-test,"subsection")]'},
    'exception_card_title': {'type': 'xpath', 'locator': '//div[contains(@data-test,"subsection")]//h3'},
    'exception_card_autor_title': {'type': 'xpath', 'locator': '(//div[contains(@data-test,"subsection")]//h5)[1]'},
    'exception_card_date_title': {'type': 'xpath', 'locator': '(//div[contains(@data-test,"subsection")]//h5)[2]'},
    'exception_card_autor_value': {'type': 'xpath', 'locator': '(//div[contains(@data-test,"subsection")]//p)[1]'},
    'exception_card_date_value': {'type': 'xpath', 'locator': '(//div[contains(@data-test,"subsection")]//p)[2]'},
    # TODO: table locators for exceptions here

    # log_margin_section
    'lm_start_date_title': {'type': 'css', 'locator': 'div[data-test="column-header-startOf"]'},
    'lm_start_date_cell': {'type': 'xpath', 'locator': '(//div[@data-test="log-margin-start-date"])[1]/div'},
    'lm_end_date_title': {'type': 'css', 'locator': 'div[data-test="column-header-endOf"]'},
    'lm_end_date_cell': {'type': 'xpath', 'locator': '(//div[@data-test="log-margin-end-date"])[1]/div'},
    'lm_category_title': {'type': 'css', 'locator': 'div[data-test="column-header-category"]'},
    'lm_category_cell': {'type': 'xpath', 'locator': '(//div[@data-test="log-margin-category"])[1]/div'},
    'lm_application_area_title': {'type': 'css', 'locator': 'div[data-test="column-header-applicationArea"]'},
    'lm_application_area_cell': {'type': 'xpath',
                                 'locator': '(//div[@data-test="log-margin-application-area"])[1]/div'},
    'lm_loc_markup_title': {'type': 'css', 'locator': 'div[data-test="column-header-locMarkup"]'},
    'lm_loc_markup_cell': {'type': 'xpath', 'locator': '(//div[@data-test="log-margin-loc-markup"])[1]/div'},
    'lm_rc_markup_title': {'type': 'css', 'locator': 'div[data-test="column-header-rcMarkup"]'},
    'lm_rc_markup_cell': {'type': 'xpath', 'locator': '(//div[@data-test="log-margin-rc-markup"])[1]/div'},
    'lm_created_by_title': {'type': 'css', 'locator': 'div[data-test="column-header-createdBy"]'},
    'lm_created_by_cell': {'type': 'xpath', 'locator': '(//span[@data-test="log-margin-created-by"])[1]'},
    'lm_updated_title': {'type': 'css', 'locator': 'div[data-test="column-header-updated"]'},
    'lm_updated_cell': {'type': 'xpath', 'locator': '(//div[@data-test="log-margin-update-date"])[1]/div'},
    'add_lm_btn': {'type': 'css', 'locator': 'button[data-test="add-log-margin"]'},
    'load_lm_btn': {'type': 'css', 'locator': 'button[data-test="load-log-margin"]'},
    'date_picker_inp': {'type': 'css', 'locator': 'div[data-test="datepicker-input"] input'},
    'date_picker_label': {'type': 'css', 'locator': 'div[data-test="datepicker-input"] label'},
    'date_picker_btn': {'type': 'css', 'locator': 'span[data-test="clickAfterIcon"]'},
    'application_area_inp': {'type': 'css', 'locator': 'div[data-test="select-application-area"] input'},
    'category_inp': {'type': 'css', 'locator': 'div[data-test="select-category"] input'},
    'regions_btn': {'type': 'xpath', 'locator':
        '//div[@data-test="select-application-area"]//div[@class="menu"]/div/div[1]/div[1]'},
    'stores_btn': {'type': 'xpath', 'locator':
        '//div[@data-test="select-application-area"]//div[@class="menu"]/div/div[1]/div[2]'},
    'first_menu_item': {'type': 'xpath', 'locator': '(//div[@class="search-filter__menu-item"]/div)[1]'},
    'loc_markup_inp': {'type': 'css', 'locator': 'div[data-test="edit-loc-markup"] input'},
    'loc_markup_label': {'type': 'css', 'locator': 'div[data-test="edit-loc-markup"] label'},
    'rc_markup_inp': {'type': 'css', 'locator': 'div[data-test="edit-rc-markup"] input'},
    'rc_markup_label': {'type': 'css', 'locator': 'div[data-test="edit-rc-markup"] label'},
    'rc_markup_id': {'type': 'xpath', 'locator': '(//div[@class="side-panel__head"]//h5)[1]'},
    'rc_markup_id_value': {'type': 'xpath', 'locator': '(//div[@class="side-panel__head"]/div/div)[1]'},
    'rc_markup_updates': {'type': 'xpath', 'locator': '(//div[@class="side-panel__head"]//h5)[2]'},
    'rc_markup_updates_value': {'type': 'xpath', 'locator': '(//div[@class="side-panel__head"]/div/div)[2]'},
    'lm_sidepanel_period_title': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(1) h5'},
    'lm_sidepanel_period_value': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(1) div'},
    'lm_sidepanel_region_title': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(2) h5'},
    'lm_sidepanel_region_value': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(2) div'},
    'lm_sidepanel_category_title': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(3) h5'},
    'lm_sidepanel_category_value': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(3) div'},
    'lm_sidepanel_loc_title': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(4) h5'},
    'lm_sidepanel_loc_value': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(4) div'},
    'lm_sidepanel_rc_title': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(5) h5'},
    'lm_sidepanel_rc_value': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(5) div'},
    'edit_lm_btn': {'type': 'css', 'locator': 'button[data-test="start-editing"]'},
    'delete_period_btn': {'type': 'css', 'locator': 'data-test="clearableInput"'},

    # holidays_section
    'holiday_name_title': {'type': 'css', 'locator': 'div[data-test="column-header-holiday"]'},
    'holiday_name_cell': {'type': 'css', 'locator': 'span[data-test="item-holiday"]'},
    'holiday_comment_title': {'type': 'css', 'locator': 'div[data-test="column-header-comment"]'},
    'holiday_comment_cell': {'type': 'css', 'locator': 'span[data-test="item-comment"]'},
    'holiday_author_title': {'type': 'css', 'locator': 'div[data-test="column-header-authorChanges"]'},
    'holiday_author_cell': {'type': 'css', 'locator': 'span[data-test="item-authorChanges"]'},
    'holiday_changes_title': {'type': 'css', 'locator': 'div[data-test="column-header-changes"]'},
    'holiday_changes_cell': {'type': 'css', 'locator': 'span[data-test="item-changes"]'},
    'add_holiday_btn': {'type': 'css', 'locator': 'button[data-test="add-log-margin"]'},
    'load_holiday_btn': {'type': 'css', 'locator': '.versatile-header__actions > button:nth-child(2)'},
    'adding_holiday_inp': {'type': 'css', 'locator': 'div[data-test="region"] input'},
    'adding_holiday_label': {'type': 'css', 'locator': 'div[data-test="region"] label'},
    'region_first_checkbox': {'type': 'xpath', 'locator': '(//div[@class="menu"]//input[@class="checkbox__input"])[2]'},
    'comment_inp': {'type': 'css', 'locator': 'div[data-test="comment"] textarea'},
    'cancel_editing_btn': {'type': 'css', 'locator': 'button[data-test="cancel-editing"]'},
    'save_changes_btn': {'type': 'css', 'locator': 'button[data-test="save-changes"]'},

    # price_reasons_section
    '1c_key_title': {'type': 'css', 'locator': '[data-test="column-header-key1c"] div'},
    '1c_key_cell': {'type': 'css', 'locator': 'span[data-test="item-key1c"]'},
    '1c_key_label': {'type': 'css', 'locator': '[data-test="key1c"] label'},
    '1c_key_value': {'type': 'css', 'locator': '[data-test="key1c"] input'},
    'reason_title': {'type': 'css', 'locator': '[data-test="column-header-reason"] div'},
    'reason_cell': {'type': 'css', 'locator': 'span[data-test="item-reason"]'},
    'reason_label': {'type': 'css', 'locator': '[data-test="reason"] label'},
    'reason_value': {'type': 'css', 'locator': '[data-test="reason"] input'},
}
