PRICE_LISTS = {
    'add_btn': {'type': 'css', 'locator': '.versatile-header__actions button'},
    'export_btn': {'type': 'css', 'locator': '.versatile-header__actions > button:nth-child(2)'},
    'page_title': {'type': 'css', 'locator': '.versatile-header__title'},
    'filter_tabs': {'type': 'css', 'locator': '.versatile-header__tabs'},
    'all_tab': {'type': 'css', 'locator': '.versatile-header__tabs div:nth-child(1)'},
    'manual_tab': {'type': 'css', 'locator': '.versatile-header__tabs div:nth-child(2)'},
    'systemic_tab': {'type': 'css', 'locator': '.versatile-header__tabs div:nth-child(3)'},
    'search_inp': {'type': 'css', 'locator': '[data-test="search"] input'},
    'filter_btn': {'type': 'css', 'locator': '[data-test="changeDropDown"]'},
    'cards': {'type': 'css', 'locator': '.card-wrap'},
    'card_name': {'type': 'css', 'locator': '.card-wrap h3 span > span'},
    'card_priority': {'type': 'css', 'locator': '.card-wrap>div:nth-child(2)>div:nth-child(1)>span:nth-child(1)'},
    'card_priority_val': {'type': 'css', 'locator': '.card-wrap>div:nth-child(2)>div:nth-child(1)>span:nth-child(2)'},
    'card_is_special': {'type': 'css', 'locator': '.card-wrap>div:nth-child(2)>div:nth-child(2)>span:nth-child(1)'},
    'card_is_special_val': {'type': 'css', 'locator': '.card-wrap>div:nth-child(2)>div:nth-child(2)>span:nth-child(2)'},
    'card_author': {'type': 'css', 'locator': '.card-wrap>div:nth-child(2)>div:nth-child(3)>span:nth-child(1)'},
    'card_author_val': {'type': 'css', 'locator': '.card-wrap>div:nth-child(2)>div:nth-child(3)>span:nth-child(2)'},
    'card_date': {'type': 'css', 'locator': '.card-wrap>div:nth-child(2)>div:nth-child(4)>span:nth-child(1)'},
    'card_date_val': {'type': 'css', 'locator': '.card-wrap>div:nth-child(2)>div:nth-child(4)>span:nth-child(2)'},
    'open_context_menu_btn': {'type': 'css', 'locator': '[data-test="toggle"]'},
    'menu_edit_btn': {'type': 'css', 'locator': '.context-menu div'},
    'system_pl_title': {'type': 'xpath', 'locator': '(//a[contains(@href, "/system/")]/span/span)[1]'},
    'system_pl_priority': {'type': 'xpath', 'locator': '(//a[contains(@href, "/system/")]/../../../div[2]/div/span[1])[1]'},
    'system_pl_priority_val': {'type': 'xpath', 'locator': '(//a[contains(@href, "/system/")]/../../../div[2]/div/span[2])[1]'},
    'type_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(1) input'},
    'type_error': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(1) .input_error-annotation'},
    'priority_inp': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(2) input'},
    'priority_error': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(2) .input_error-annotation'},
    'is_special': {'type': 'css', 'locator': '.side-panel__content > div:nth-child(3) span:nth-child(1)'},
    'true_radio': {'type': 'css', 'locator': '.side-panel__content .radio:nth-of-type(1) span:nth-of-type(1)'},
    'false_radio': {'type': 'css', 'locator': '.side-panel__content .radio:nth-of-type(2) span:nth-of-type(1)'},
    'true_label': {'type': 'css', 'locator': '.side-panel__content .radio:nth-of-type(1) span:nth-of-type(2)'},
    'false_label': {'type': 'css', 'locator': '.side-panel__content .radio:nth-of-type(2) span:nth-of-type(2)'},
    'comment': {'type': 'css', 'locator': '.side-panel__content textarea'},
    'save_btn': {'type': 'css', 'locator': '.side-panel__foot button:nth-child(2)'},
    'cancel_btn': {'type': 'css', 'locator': '.side-panel__foot button:nth-child(1)'},
    'no_data_text': {'type': 'css', 'locator': '.no-data__text'},

    # price list page
    'title_header': {'type': 'css', 'locator': '[data-test="column-header-title"]'},
    'priority_header': {'type': 'css', 'locator': '[data-test="column-header-params.priority"]'},
    'special_header': {'type': 'css', 'locator': '[data-test="column-header-params.special"]'},
    'comment_header': {'type': 'css', 'locator': '[data-test="column-header-comment"]'},
    'status_header': {'type': 'css', 'locator': '[data-test="column-header-status"]'},
    'author_header': {'type': 'css', 'locator': '[data-test="column-header-params.author"]'},
    'date_change_header': {'type': 'css', 'locator': '[data-test="column-header-params.dateChange"]'},
    'price_list_type_inp': {'type': 'css', 'locator': '.side-panel__content > :nth-child(1) input'},
    'check_value_inp': {'type': 'css', 'locator': '.side-panel__content > :nth-child(2) input'},
    'check_value_btn': {'type': 'css', 'locator': '[data-test="toggleShowMenu"] > div > div'},
    'postfix_inp': {'type': 'css', 'locator': '.side-panel__content > :nth-child(3) input'},
    'search_item': {'type': 'css', 'locator': '.search-filter__menu > :nth-child(2) .search-filter__item'},
    'first_row': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(1) a'},
    'check_first_row': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(1) a > '
                                                  ':nth-child(1) span.checkbox__control'},
    'second_row': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(2) a'},
    'check_second_row': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(2) a > '
                                                   ':nth-child(1) span.checkbox__control'},
    'third_row': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(3) a'},
    'fourth_row': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(4) a'},
    'check_third_row': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(3) a > '
                                                  ':nth-child(1) span.checkbox__control'},
    'footer': {'type': 'css', 'locator': '.advanced-flex-table-bottom-panel'},
    'footer_info': {'type': 'css', 'locator': '.advanced-flex-table-bottom-panel__info'},
    'footer_cancel_btn': {'type': 'css', 'locator': '[data-test="uncheckAll"]'},
    'check_all_rows': {'type': 'css', 'locator': '.flex-table__header span.checkbox__control'},
}
