PRICE_CALCULATING = {
    # table
    'page_title': {'type': 'css', 'locator': 'h1.versatile-header__title'},
    'start_recalculation_btn': {'type': 'css', 'locator': 'div.versatile-header__actions button:nth-child(2)'},
    'confirm_btn': {'type': 'css', 'locator': 'button[data-test="confirm"]'},
    'download_btn': {'type': 'css', 'locator': 'div.versatile-header__actions button:nth-child(3)'},
    'uploaded_data': {'type': 'css', 'locator': 'p.versatile-header__info-line:nth-child(1)'},
    'confirmed_data': {'type': 'css', 'locator': 'p.versatile-header__info-line:nth-child(2)'},
    'all_prices_btn': {'type': 'xpath', 'locator': '//div[@role="button" and contains(text(), "Всего цен")]'},
    'without_changes_btn': {'type': 'xpath', 'locator': '//div[@role="button" and contains(text(), "Без изменений")]'},
    'new_btn': {'type': 'xpath', 'locator': '//div[@role="button" and contains(text(), "Новые")]'},
    'close_btn': {'type': 'xpath', 'locator': '//div[@role="button" and contains(text(), "Закрытие")]'},
    'increase_btn': {'type': 'xpath', 'locator': '//div[@role="button" and contains(text(), "Повышение")]'},
    'decrease_btn': {'type': 'xpath', 'locator': '//div[@role="button" and contains(text(), "Снижение")]'},
    'first_row': {'type': 'css', 'locator': '.flex-table__body > div > div > :nth-child(1) a[role=button]'},
    'icon_title': {'type': 'css', 'locator': 'div[data-test="column-header-icon"]'},
    'start_title': {'type': 'css', 'locator': 'div[data-test="column-header-startDate"]'},
    'end_title': {'type': 'css', 'locator': 'div[data-test="column-header-endDate"]'},
    'price_list_title': {'type': 'css', 'locator': 'div[data-test="column-header-priceList"]'},
    'code_title': {'type': 'css', 'locator': 'div[data-test="column-header-code"]'},
    'nomenclature_title': {'type': 'css', 'locator': 'div[data-test="column-header-nomenclature"]'},
    'price_title': {'type': 'css', 'locator': 'div[data-test="column-header-price"]'},
    'promo_title': {'type': 'css', 'locator': 'div[data-test="column-header-promo"]'},
    'cause_title': {'type': 'css', 'locator': 'div[data-test="column-header-cause"]'},
    'status_cell': {'type': 'css', 'locator': '[data-test="pricing-status"]'},
    'status_tooltip': {'type': 'xpath', 'locator': '(//div[@data-test="pricing-status"]/../div[2])[1]'},
    'start_date_cell': {'type': 'css', 'locator': 'div[data-test="pricing-start-date"]'},
    'end_date_cell': {'type': 'css', 'locator': 'div[data-test="pricing-end-date"]'},
    'price_list_cell': {'type': 'css', 'locator': 'span[data-test="pricing-price-list"]'},
    'code_cell': {'type': 'css', 'locator': 'div[data-test="pricing-code"]'},
    'nomenclature_cell': {'type': 'css', 'locator': 'span[data-test="pricing-nomenclature"]'},
    'nomenclature_tooltip': {'type': 'xpath', 'locator': '(//span[@data-test="pricing-nomenclature"]/../div)[1]'},
    'price_cell': {'type': 'css', 'locator': 'span[data-test="pricing-price"]'},
    'promo_cell': {'type': 'css', 'locator': 'a[role=button] div.flex-table-cell:nth-child(8)'},
    'cause_cell': {'type': 'css', 'locator': 'div[data-test="pricing-cause"]'},
    'table': {'type': 'css', 'locator': 'div.flex-table'},

    #
    'go_to_rule_btn': {'type': 'css', 'locator': '.side-panel__head button'},
    'previous_price_title': {'type': 'css', 'locator': 'div.text-additional h5'},
    'last_price_title': {'type': 'css', 'locator': 'h5.text-additional'},
    'previous_price_value': {'type': 'xpath', 'locator': '(//div[@class="side-panel__head"]//p)[1]'},
    'last_price_value': {'type': 'xpath', 'locator': '(//div[@class="side-panel__head"]//p)[2]'},
    'info_tab': {'type': 'css', 'locator': '.side-panel__head .tab:nth-of-type(1)'},
    'stages_tab': {'type': 'css', 'locator': '.side-panel__head .tab:nth-of-type(2)'},
    'status_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(1) h5'},
    'status_value': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(1) .side-panel-info-item__value'},
    'nomenclature_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(2) h5'},
    'nomenclature_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(2) div'},
    'date_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(3) h5'},
    'date_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(3) div'},
    'price_list_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(4) h5'},
    'price_list_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(4) div'},
    'code_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(5) h5'},
    'code_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(5) div'},
    'promo_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(6) h5'},
    'promo_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(5) div'},
    'cause_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(7) h5'},
    'cause_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(7) div'},
    'locality_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(8) h5'},
    'locality_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(8) div'},
    'comment_label': {'type': 'css', 'locator': '.side-panel__content div div:nth-child(9) h5'},
    'comment_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(9) div'},
    'delete_row_btn': {'type': 'css', 'locator': 'button[data-test="delete-row"]'},
    'open_pricing_btn': {'type': 'css', 'locator': '.price-calculating button'},

    # need refactoring
    'clipping_monitoring_title': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__caption"])[1]'},
    'checking_calculating_object_title': {'type': 'xpath',
                                          'locator': '(//h5[@class="side-panel-info-item__caption"])[2]'},
    'kib_exchange_title': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__caption"])[3]'},
    'round_price_title': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__caption"])[4]'},
    'is_residues_title': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__caption"])[5]'},
    'is_monitoring_title': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__caption"])[6]'},
    'counting_number_prices_title': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__caption"])[7]'},
    'percentile_calculation_title': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__caption"])[8]'},
    'complex_discounts_title': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__caption"])[9]'},
    'sku_type_title': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__caption"])[10]'},
    'clipping_monitoring_value': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__value"])[1]'},
    'checking_calculating_object_value': {'type': 'xpath',
                                          'locator': '(//h5[@class="side-panel-info-item__value"])[2]'},
    'kib_exchange_value': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__value"])[3]'},
    'round_price_value': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__value"])[4]'},
    'is_residues_value': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__value"])[5]'},
    'is_monitoring_value': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__value"])[6]'},
    'counting_number_prices_value': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__value"])[7]'},
    'percentile_calculation_value': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__value"])[8]'},
    'complex_discounts_value': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__value"])[9]'},
    'sku_type_value': {'type': 'xpath', 'locator': '(//h5[@class="side-panel-info-item__value"])[10]'},
}
