PRICE_LISTS = {
    # price-lists types
    'pl_type_inp': {'type': 'css', 'locator': 'div[data-test="type"] input'},
    'pl_type_label': {'type': 'css', 'locator': 'div[data-test="type"] label'},
    'pl_type_btn': {'type': 'css', 'locator': 'div[data-test="select-region"] span'},
    'pl_comment_inp': {'type': 'css', 'locator': '.side-panel__content div'},
    'pl_type_comment_label': {'type': 'css', 'locator': '.side-panel__content h5'},
    'pl_type_title': {'type': 'css', 'locator': '[data-test="column-header-type"] div'},
    'pl_type_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(1) div span'},
    'comment_title': {'type': 'css', 'locator': '[data-test="column-header-comment"] div'},
    'comment_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(2) div span'},
    'author_title': {'type': 'css', 'locator': '[data-test="column-header-author"] div'},
    'author_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(3) div span'},
    'changes_date_title': {'type': 'css', 'locator': '[data-test="column-header-changesDate"] div'},
    'changes_date_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(4) div span'},

    # virtual departments
    'region_title': {'type': 'css', 'locator': '[data-test="column-header-region"] div'},
    'region_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(1) div'},
    'region_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(1) div'},
    'region_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(1) h5'},
    'locality_title': {'type': 'css', 'locator': '[data-test="column-header-locality"] div'},
    'locality_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(2) div'},
    'comment_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(2) div'},
    'comment_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(2) h5'},
    'vd_comment_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(3) div'},
    'updated_by_title': {'type': 'css', 'locator': '[data-test="column-header-updatedBy"] div'},
    'updated_by_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(4) div'},
    'updated_title': {'type': 'css', 'locator': '[data-test="column-header-updated"] div'},
    'updated_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(5) div'},
    'create_vd_btn': {'type': 'css', 'locator': 'button[data-test=create-virtual-department]'},
    'download_vd_btn': {'type': 'css', 'locator': 'button[data-test=download-virtual-departments]'},
    'region_inp': {'type': 'css', 'locator': 'div[data-test="select-region"] input'},
    # 'region_label': {'type': 'css', 'locator': 'div[data-test="select-region"] label'},
    'region_btn': {'type': 'css', 'locator': 'div[data-test="select-region"] span'},
    # 'comment_inp': {'type': 'css', 'locator': 'div[data-test="enter-comment"] textarea'},
    # 'comment_label': {'type': 'css', 'locator': 'div[data-test="enter-comment"] label'},

    # creating connections
    'download_connections_btn': {'type': 'css', 'locator': 'button[data-test="download"]'},
    'add_connection_btn': {'type': 'css', 'locator': 'button[data-test="add"]'},

    # price_lists
    '1c_key_title': {'type': 'css', 'locator': '[data-test="column-header-key"] div'},
    '1c_key_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(1) div'},
    '1c_key_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(1) div'},
    '1c_key_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(1) h5'},
    'group_title': {'type': 'css', 'locator': '[data-test="column-header-group"] div'},
    'group_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(2) div'},
    'group_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(2) div'},
    'group_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(2) h5'},
    'name_title': {'type': 'css', 'locator': '[data-test="column-header-name"] div'},
    'name_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(3) div'},
    'name_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(3) div'},
    'name_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(3) h5'},
    'priority_title': {'type': 'css', 'locator': '[data-test="column-header-priority"] div'},
    'priority_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(4) div'},
    'priority_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(4) div'},
    'priority_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(4) h5'},
    'is_special_title': {'type': 'css', 'locator': '[data-test="column-header-isSpecial"] div'},
    'is_special_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(5) div'},
    'is_special_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(5) div'},
    'is_special_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(5) h5'},
    'pl_comment_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(6) div'},
    'pl_comment_value': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(6) div'},
    'pl_comment_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(6) h5'},

    # stores price lists
    'spl_1c_key_title': {'type': 'css', 'locator': '[data-test="column-header-key1c"] div'},
    'spl_1c_key_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(1) div'},
    'spl_region_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(2) div'},
    'subdivision_title': {'type': 'css', 'locator': '[data-test="column-header-department"] div'},
    'subdivision_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(3) div'},
    'price_list_title': {'type': 'css', 'locator': '[data-test="column-header-priceList"] div'},
    'price_list_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(4) div'},
    'start_date_title': {'type': 'css', 'locator': '[data-test="column-header-startDate"] div'},
    'start_date_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(5) div'},
    'end_date_title': {'type': 'css', 'locator': '[data-test="column-header-endDate"] div'},
    'end_date_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(6) div'},
    'spl_comment_cell': {'type': 'css', 'locator': '.flex-table__body a div:nth-child(7) div'},
    'spl_1c_value': {'type': 'css', 'locator': '[data-test="key1c"] input'},
    'spl_1c_label': {'type': 'css', 'locator': '[data-test="key1c"] label'},
    'spl_region_value': {'type': 'css', 'locator': '[data-test="region"] input'},
    'spl_region_label': {'type': 'css', 'locator': '[data-test="region"] label'},
    'subdivision_id_value': {'type': 'css', 'locator': '[data-test="departmentId"] input'},
    'subdivision_id_label': {'type': 'css', 'locator': '[data-test="departmentId"] label'},
    'subdivision_value': {'type': 'css', 'locator': '[data-test="address"] input'},
    'subdivision_label': {'type': 'css', 'locator': '[data-test="address"] label'},
    'price_list_value': {'type': 'css', 'locator': '[data-test="priceList"] input'},
    'price_list_label': {'type': 'css', 'locator': '[data-test="priceList"] label'},
    'dates_value': {'type': 'css', 'locator': '[data-test="dates"] input'},
    'dates_label': {'type': 'css', 'locator': '[data-test="dates"] label'},
    'spl_comment_value': {'type': 'css', 'locator': '[data-test="comment"] textarea'},
    'spl_comment_label': {'type': 'css', 'locator': '[data-test="comment"] label'},
}
