RULES = {
    # list of rules locators
    'create_rule_btn': {'type': 'css', 'locator': '[data-test="createRule"]'},
    'cancel_create_rule_btn': {'type': 'css', 'locator': '.rule-setup__actions > button'},
    'back_btn': {'type': 'css', 'locator': '.rule-setup__actions> div > button:nth-child(1)'},
    'continue_first_step_btn': {'type': 'css', 'locator': '[data-test="next"]'},
    'continue_btn': {'type': 'css', 'locator': '[data-test="next"]'},
    'save_rule_btn': {'type': 'css', 'locator': '[data-test="saveRule"]'},
    'rule_card': {'type': 'css', 'locator': '.card-wrap'},
    'rule_card_name': {'type': 'css', 'locator': '.card-wrap h3 span.text-lg-medium'},
    'rule_card_period': {'type': 'css', 'locator': '.card-wrap .info-item:nth-child(1) h5'},
    'rule_card_period_val': {'type': 'css', 'locator': '.card-wrap .info-item:nth-child(1) p'},
    'rule_card_author': {'type': 'css', 'locator': '.card-wrap .info-item:nth-child(2) h5'},
    'rule_card_author_val': {'type': 'css', 'locator': '.card-wrap .info-item:nth-child(2) p'},
    'rule_card_date': {'type': 'css', 'locator': '.card-wrap .info-item:nth-child(3) h5'},
    'rule_card_date_val': {'type': 'css', 'locator': '.card-wrap .info-item:nth-child(3) p'},
    'rule_card_id': {'type': 'css', 'locator': '.card-wrap > div:nth-child(2)'},
    'card_toggle_label': {'type': 'css', 'locator': '[data-test="toggleRun"]'},
    'context_menu_edit_btn': {'type': 'css', 'locator': '.context-menu > div:nth-child(1)'},
    'context_menu_delete_btn': {'type': 'css', 'locator': '.context-menu > div:nth-child(2)'},
    'context_menu_open_btn': {'type': 'css', 'locator': '.card-wrap [data-test="toggle"] div'},
    'search_inp': {'type': 'css', 'locator': '.input--search'},
    'cards': {'type': 'css', 'locator': '.card-wrap'},
    'filter_btn': {'type': 'css', 'locator': '[data-test="changeDropDown"]'},
    'step_number_1': {'type': 'css', 'locator': '[data-test="step:0"] div'},
    'step_number_2': {'type': 'css', 'locator': '[data-test="step:1"] div'},
    'step_number_3': {'type': 'css', 'locator': '[data-test="step:2"] div'},
    'step_number_4': {'type': 'css', 'locator': '[data-test="step:3"] div'},
    'step_number_5': {'type': 'css', 'locator': '[data-test="step:4"] div'},
    'step_number_1_label': {'type': 'css', 'locator': '[data-test="step:0"] p'},
    'step_number_2_label': {'type': 'css', 'locator': '[data-test="step:1"] p'},
    'step_number_3_label': {'type': 'css', 'locator': '[data-test="step:2"] p'},
    'step_number_4_label': {'type': 'css', 'locator': '[data-test="step:3"] p'},
    'step_number_5_label': {'type': 'css', 'locator': '[data-test="step:4"] p'},
    'back_to_main_btn': {'type': 'css', 'locator': '.back span'},
    '1st_rule_toggle': {'type': 'css', 'locator': '.rules-list>div[role="button"]:nth-child(1) label > input'},
    'last_rule_open_menu_btn': {'type': 'xpath', 'locator': '(//div[@data-test="toggle"])[last()]/div[1]'},
    'last_rule_delete_btn': {'type': 'xpath', 'locator': '(//div[contains(text(), "Удалить")])[last()]'},
    'last_rule_name': {'type': 'xpath', 'locator': '(//div[contains(@data-test, "rule")])[last()]//h3/span/span/span'},
    'popup_title': {'type': 'css', 'locator': '.modal-header h5'},
    'popup_body_text': {'type': 'css', 'locator': '.modal-body div'},
    'popup_cancel_btn': {'type': 'css', 'locator': '.modal-footer [data-test="close"]'},
    'popup_confirm_btn': {'type': 'css', 'locator': '.modal-footer [data-test="confirm"]'},

    # first step
    'rule_name_inp': {'type': 'css', 'locator': '[data-test="enterRuleName"] input'},
    'store_connections_inp': {'type': 'css', 'locator': 'div[data-test="toggleShowMenu"] input'},
    'period_inp': {'type': 'css', 'locator': 'div[data-test="datepicker-input"] input'},
    'period_label': {'type': 'css', 'locator': 'div[data-test="datepicker-input"] label'},
    'header_title': {'type': 'css', 'locator': '.main-info__header .rule-setup__title'},
    'header_description': {'type': 'css', 'locator': '.main-info__header .rule-setup__descr'},
    'repeat_title': {'type': 'css', 'locator': '.main-info > div:nth-child(2) .rule-setup__title'},
    'repeat_description': {'type': 'css', 'locator': '.main-info > div:nth-child(2) .rule-setup__descr'},
    'delivery_title': {'type': 'css', 'locator': '.main-info > div:nth-child(3) .rule-setup__title'},
    'delivery_description': {'type': 'css', 'locator': '.main-info > div:nth-child(3) .rule-setup__descr'},
    'daily_span': {'type': 'xpath', 'locator': '//input[@value="daily"]/../span[1]'},
    'daily_name': {'type': 'xpath', 'locator': '//input[@value="daily"]/../span[2]'},
    'daily_label': {'type': 'css', 'locator': '.rule-setup__block >.main-info__radio-wrap > label:nth-child(1)'},
    'weekly_span': {'type': 'xpath', 'locator': '//input[@value="weekly"]/../span[1]'},
    'weekly_name': {'type': 'xpath', 'locator': '//input[@value="weekly"]/../span[2]'},
    'monthly_span': {'type': 'xpath', 'locator': '//input[@value="monthly"]/../span[1]'},
    'monthly_name': {'type': 'xpath', 'locator': '//input[@value="monthly"]/../span[2]'},

    'no_data_text': {'type': 'css', 'locator': '.no-data__text'},
    'schedule_span': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(3) .radio:nth-child(1) .radio__control'},
    'schedule_label': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(3) .radio:nth-child(1) .radio__label'},
    'manual_span': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(3) .radio:nth-child(2) .radio__control'},
    'manual_label': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(3) .radio:nth-child(2) .radio__label'},
    'schedule_title': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(3) h4'},
    'delta_title': {'type': 'css', 'locator': '.rule-setup__subtitle:nth-of-type(1) p'},
    'full_title': {'type': 'css', 'locator': '.rule-setup__subtitle:nth-of-type(2) p'},
    'mon_checkbox': {'type': 'xpath', 'locator': '(//input[@value="Пн"]/../span)[1]'},
    'mon_name': {'type': 'xpath', 'locator': '(//input[@value="Пн"]/../span)[2]'},
    'tue_checkbox': {'type': 'xpath', 'locator': '(//input[@value="Вт"]/../span)[1]'},
    'tue_name': {'type': 'xpath', 'locator': '(//input[@value="Вт"]/../span)[2]'},
    'wed_checkbox': {'type': 'xpath', 'locator': '(//input[@value="Ср"]/../span)[1]'},
    'wed_name': {'type': 'xpath', 'locator': '(//input[@value="Ср"]/../span)[2]'},
    'thu_checkbox': {'type': 'xpath', 'locator': '(//input[@value="Чт"]/../span)[1]'},
    'thu_name': {'type': 'xpath', 'locator': '(//input[@value="Чт"]/../span)[2]'},
    'fri_checkbox': {'type': 'xpath', 'locator': '(//input[@value="Пт"]/../span)[1]'},
    'fri_name': {'type': 'xpath', 'locator': '(//input[@value="Пт"]/../span)[2]'},
    'sat_checkbox': {'type': 'xpath', 'locator': '(//input[@value="Сб"]/../span)[1]'},
    'sat_name': {'type': 'xpath', 'locator': '(//input[@value="Сб"]/../span)[2]'},
    'sun_checkbox': {'type': 'xpath', 'locator': '(//input[@value="Вс"]/../span)[1]'},
    'sun_name': {'type': 'xpath', 'locator': '(//input[@value="Вс"]/../span)[2]'},
    'full_mon_checkbox': {'type': 'xpath', 'locator': '(//input[@value="Пн"]/../span)[3]'},
    'full_mon_name': {'type': 'xpath', 'locator': '(//input[@value="Пн"]/../span)[4]'},
    'full_tue_checkbox': {'type': 'xpath', 'locator': '(//input[@value="Вт"]/../span)[3]'},
    'full_tue_name': {'type': 'xpath', 'locator': '(//input[@value="Вт"]/../span)[4]'},
    'full_wed_checkbox': {'type': 'xpath', 'locator': '(//input[@value="Ср"]/../span)[3]'},
    'full_wed_name': {'type': 'xpath', 'locator': '(//input[@value="Ср"]/../span)[4]'},
    'full_thu_checkbox': {'type': 'xpath', 'locator': '(//input[@value="Чт"]/../span)[3]'},
    'full_thu_name': {'type': 'xpath', 'locator': '(//input[@value="Чт"]/../span)[4]'},
    'full_fri_checkbox': {'type': 'xpath', 'locator': '(//input[@value="Пт"]/../span)[3]'},
    'full_fri_name': {'type': 'xpath', 'locator': '(//input[@value="Пт"]/../span)[4]'},
    'full_sat_checkbox': {'type': 'xpath', 'locator': '(//input[@value="Сб"]/../span)[3]'},
    'full_sat_name': {'type': 'xpath', 'locator': '(//input[@value="Сб"]/../span)[4]'},
    'full_sun_checkbox': {'type': 'xpath', 'locator': '(//input[@value="Вс"]/../span)[3]'},
    'full_sun_name': {'type': 'xpath', 'locator': '(//input[@value="Вс"]/../span)[4]'},
    'exclude_holidays_inp': {'type': 'css', 'locator': '.repetition-period__holidays-exclusion-checkbox input'},
    'exclude_holidays_checkbox': {'type': 'css',
                                  'locator': '.repetition-period__holidays-exclusion-checkbox .checkbox__control'},
    'exclude_holidays_name': {'type': 'css',
                              'locator': '.repetition-period__holidays-exclusion-checkbox .checkbox__label'},
    'auto_recalculation_time_inp': {'type': 'css', 'locator': '[data-test="enterRepetitionPeriodTime"] input'},
    'auto_recalculation_time_txt': {'type': 'css', 'locator': '.rule-setup__subtitle:nth-of-type(1)'},
    'default_txt': {'type': 'css', 'locator': '.main-info>div:nth-child(2)>div:nth-child(6)'},

    # second step
    'selection_section_title': {'type': 'css', 'locator': '.head__main h2'},
    'before_selection_title': {'type': 'css', 'locator': 'h2.selection-base__title'},
    'before_selection_txt': {'type': 'css', 'locator': 'p.selection-base__prompt'},
    'selection_section_txt': {'type': 'css', 'locator': '.head__main p'},
    'use_directory_btn': {'type': 'css', 'locator': '.card-container > div:nth-child(1)'},
    'use_directory_title': {'type': 'css', 'locator': '.card-container > div:nth-child(1) h4'},
    'use_directory_txt': {'type': 'css', 'locator': '.card-container > div:nth-child(1) p'},
    'use_file_btn': {'type': 'css', 'locator': '.card-container > div:nth-child(2)'},
    'use_file_title': {'type': 'css', 'locator': '.card-container > div:nth-child(2) h4'},
    'use_file_txt': {'type': 'css', 'locator': '.card-container > div:nth-child(2) p'},
    'file_page_header': {'type': 'css', 'locator': '.head__main h2'},
    'file_page_description': {'type': 'css', 'locator': '.head__main p'},
    'select_file_btn': {'type': 'css', 'locator': '[data-test="selectFile"]'},
    'file_inp': {'type': 'css', 'locator': 'input[data-test="fileDialogControl"]'},
    'filename': {'type': 'css', 'locator': '.selection-section__setup > div > div > div > div > div:nth-child(1)'},
    'show_results_btn': {'type': 'css', 'locator': '[data-test=showResults]'},
    'use_directory_in_file_btn': {'type': 'css', 'locator': '[data-test=openActionModal]'},
    'update_file_btn': {'type': 'css', 'locator': '[data-test=openFileDialog]'},
    'use_file_in_directory_btn': {'type': 'css', 'locator': '[data-test=act]'},
    'subdivisions_inp': {'type': 'css', 'locator': '[data-test=selectDepartments] input'},
    'subdivisions_dropdown_btn': {'type': 'css', 'locator': '[data-test=selectDepartments] div.input__icon_wrapper'},
    'treeview_search_inp': {'type': 'css', 'locator': '[data-test=treeview-selection-search] input'},
    'check_all': {'type': 'css', 'locator': '.treeview-selection__master-checkbox .checkbox__control'},
    'check_all_label': {'type': 'css', 'locator': '.treeview-selection__master-checkbox .checkbox__label'},
    'check_first_item': {'type': 'css', 'locator': '[data-test=treeview-selection-item]:nth-of-type(1) '
                                                   '.checkbox__control'},
    'first_item_label': {'type': 'css', 'locator': '[data-test=treeview-selection-item]:nth-of-type(1) '
                                                   '.checkbox__label'},
    'expand_first_item': {'type': 'css', 'locator': '[data-test=treeview-selection-item]:nth-of-type(1) button'},
    'check_second_item': {'type': 'css', 'locator': '[data-test=treeview-selection-item]:nth-of-type(2) '
                                                    '.checkbox__control'},
    'second_item_label': {'type': 'css', 'locator': '[data-test=treeview-selection-item]:nth-of-type(2) '
                                                    '.checkbox__label'},
    'expand_second_item': {'type': 'css', 'locator': '[data-test=treeview-selection-item]:nth-of-type(2) button'},
    'check_third_item': {'type': 'css', 'locator': '[data-test=treeview-selection-item]:nth-of-type(3) '
                                                   '.checkbox__control'},
    'third_item_label': {'type': 'css', 'locator': '[data-test=treeview-selection-item]:nth-of-type(3) '
                                                   '.checkbox__label'},
    'expand_third_item': {'type': 'css', 'locator': '[data-test=treeview-selection-item]:nth-of-type(3) button'},
    'treeview_breadcrumbs': {'type': 'css', 'locator': '[data-test=treeview-selection-breadcrumbs]'},
    'base_breadcrumb': {'type': 'css', 'locator': '.steps-wrap li:nth-of-type(1)'},
    'second_breadcrumb': {'type': 'css', 'locator': '.steps-wrap li:nth-of-type(2)'},
    'third_breadcrumb': {'type': 'css', 'locator': '.steps-wrap li:nth-of-type(3)'},
    'fourth_breadcrumb': {'type': 'css', 'locator': '.steps-wrap li:nth-of-type(4)'},
    'close_popup_btn': {'type': 'css', 'locator': '[data-test=closePopper]'},
    'unselect_all_btn': {'type': 'css', 'locator': '[data-test=unselectAll]'},
    'apply_btn': {'type': 'css', 'locator': '[data-test=apply]'},
    'stores_inp': {'type': 'css', 'locator': '[data-test=toggleShowMenu] input'},
    'stores_dropdown_btn': {'type': 'css', 'locator': '[data-test=toggleShowMenu] span'},
    'divisions_filter_btn': {'type': 'css', 'locator': '[data-test=changeDropDown]'},
    'subdivisions_wrap': {'type': 'css', 'locator': '.steps-wrap'},
    'sceleton_item': {'type': 'css', 'locator': '[data-test=item-skeleton]'},

    # shops table
    'name_title': {'type': 'css', 'locator': '[data-test="column-header-name"]'},
    'status_title': {'type': 'css', 'locator': '[data-test="column-header-status"]'},
    'contestant_title': {'type': 'css', 'locator': '[data-test="column-header-contestant"]'},
    'distance_title': {'type': 'css', 'locator': '[data-test="column-header-distance"]'},
    'organization_title': {'type': 'css', 'locator': '[data-test="column-header-organization"]'},
    'division_title': {'type': 'css', 'locator': '[data-test="column-header-division"]'},
    'region_title': {'type': 'css', 'locator': '[data-test="column-header-region"]'},
    'locality_title': {'type': 'css', 'locator': '[data-test="column-header-locality"]'},
    'department_code_title': {'type': 'css', 'locator': '[data-test="column-header-departmentCode"]'},
    'name_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(1) div'},
    'status_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(2) div'},
    'contestant_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(3) div'},
    'distance_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(4) div'},
    'organization_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(5) div'},
    'division_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(6) div'},
    'region_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(7) div'},
    'locality_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(8) div'},
    'department_code_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(9) div'},
    'first_row': {'type': 'css', 'locator': '.flex-table__body>div>div>:nth-child(1) .flex-table-row'},

    # third step
    'nomenclature_inp': {'type': 'css', 'locator': '[data-test="selectProducts"] input'},
    'nomenclature_dropdown_btn': {'type': 'css', 'locator': '[data-test="selectProducts"] .input__icon_wrapper'},

    # products table
    'assortment_type_title': {'type': 'css', 'locator': '[data-test="column-header-assortmentType"]'},
    'vtm_title': {'type': 'css', 'locator': '[data-test="column-header-vtm"]'},
    'brand_title': {'type': 'css', 'locator': '[data-test="column-header-brand"]'},
    'import_title': {'type': 'css', 'locator': '[data-test="column-header-import"]'},
    'category_title': {'type': 'css', 'locator': '[data-test="column-header-category"]'},
    'group_title': {'type': 'css', 'locator': '[data-test="column-header-group"]'},
    'subgroup_title': {'type': 'css', 'locator': '[data-test="column-header-subgroup"]'},
    'product_code_title': {'type': 'css', 'locator': '[data-test="column-header-code"]'},
    'assortment_type_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(2) div'},
    'vtm_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(3) div'},
    'brand_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(4) div'},
    'import_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(5) div'},
    'category_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(6) div'},
    'group_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(7) div'},
    'subgroup_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(8) div'},
    'product_code_cell': {'type': 'css', 'locator': '.flex-table__body [role="row"] div:nth-child(9) div'},

    # 4th step
    '4th_step_title': {'type': 'css', 'locator': '.rule-setup__title'},
    '4th_step_description': {'type': 'css', 'locator': '.rule-setup__descr'},
    'search': {'type': 'css', 'locator': '.input__wrapper input'},
    'search_family_product_btn': {'type': 'css', 'locator': '[data-test="base-condition-1203"]'},
    'percentile_btn': {'type': 'css', 'locator': '[data-test="base-condition-1103"]'},
    'monitoring_btn': {'type': 'css', 'locator': '[data-test="base-condition-1201"]'},
    'rounding_btn': {'type': 'css', 'locator': '[data-test="base-condition-1101"]'},
    'prices_counting_btn': {'type': 'css', 'locator': '[data-test="base-condition-1202"]'},
    'adding_to_price_btn': {'type': 'css', 'locator': '[data-test="base-condition-1104"]'},
    'balance_checking_btn': {'type': 'css', 'locator': '[data-test="base-condition-1204"]'},
    'complex_discounts_checking_btn': {'type': 'css', 'locator': '[data-test="base-condition-1205"]'},
    'monitoring_clipping_btn': {'type': 'css', 'locator': '[data-test="base-condition-1102"]'},
    'check_rubles_kopecks_btn': {'type': 'css', 'locator': '[data-test="base-condition-1208"]'},
    'sprice_btn': {'type': 'css', 'locator': '[data-test="base-condition-1105"]'},
    'conversion_factor_check_btn': {'type': 'css', 'locator': '[data-test="base-condition-1206"]'},
    'kib_reason_btn': {'type': 'css', 'locator': '[data-test="base-condition-1207"]'},
    'recalculating_coefficient_btn': {'type': 'css', 'locator': '[data-test="base-condition-1106"]'},
    'check_rubles_kopecks_txt': {'type': 'css', 'locator': '[data-test="base-condition-1208"] span'},
    'sprice_txt': {'type': 'css', 'locator': '[data-test="base-condition-1105"] span'},
    'conversion_factor_check_txt': {'type': 'css', 'locator': '[data-test="base-condition-1206"] span'},
    'kib_reason_txt': {'type': 'css', 'locator': '[data-test="base-condition-1207"] span'},
    'recalculating_coefficient_txt': {'type': 'css', 'locator': '[data-test="base-condition-1106"] span'},
    'search_family_product_txt': {'type': 'css', 'locator': '[data-test="base-condition-1203"] span'},
    'percentile_txt': {'type': 'css', 'locator': '[data-test="base-condition-1103"] span'},
    'monitoring_txt': {'type': 'css', 'locator': '[data-test="base-condition-1201"] span'},
    'rounding_txt': {'type': 'css', 'locator': '[data-test="base-condition-1101"] span'},
    'prices_counting_txt': {'type': 'css', 'locator': '[data-test="base-condition-1202"] span'},
    'adding_to_price_txt': {'type': 'css', 'locator': '[data-test="base-condition-1104"] span'},
    'balance_checking_txt': {'type': 'css', 'locator': '[data-test="base-condition-1204"] span'},
    'complex_discounts_checking_txt': {'type': 'css', 'locator': '[data-test="base-condition-1205"] span'},
    'monitoring_clipping_txt': {'type': 'css', 'locator': '[data-test="base-condition-1102"] span'},
    'empty_conditions_txt': {'type': 'css', 'locator': '.conditions-building__body > div:nth-child(2) '
                                                       '.text-additional-300'},
    'conditions_search_inp': {'type': 'css', 'locator': '[data-test="search"] input'},
    'condition_card_name': {'type': 'xpath', 'locator': '//div[contains(@data-test, "rule-condition")]//h3//span/span'},
    'condition_card_id': {'type': 'xpath',
                          'locator': '(//div[contains(@data-test, "rule-condition")]//span)[4]'},
    'condition_card_status': {'type': 'css',
                              'locator': '[data-test="rule-condition-undefined"] div div span:nth-of-type(2)'},
    'condition_card_custom_name': {'type': 'xpath',
                                   'locator': '//div[contains(@data-test, "rule-condition")]/div[2]/div[1]'},
    'condition_header_title': {'type': 'css', 'locator': '.conditions-building__header>:nth-child(2)>div'},
    'condition_save_btn': {'type': 'css', 'locator': '.conditions-building__header>:nth-child(2)>button'},
    'further_title': {'type': 'css', 'locator': '.conditions-building__body .rule-setup__title:nth-of-type(1)'},
    'further_desc': {'type': 'xpath', 'locator': '(//div[contains(@class, "rule-setup__descr")])[2]'},
    'otherwise_title': {'type': 'css', 'locator': '.conditions-building__body .rule-setup__title:nth-of-type(2)'},
    'otherwise_desc': {'type': 'xpath', 'locator': '(//div[contains(@class, "rule-setup__descr")])[3]'},
    'next_condition_type_inp_1': {'type': 'css', 'locator': '[data-test="nextConditionType-1"] input'},
    'next_condition_type_inp_2': {'type': 'css', 'locator': '[data-test="nextConditionType-2"] input'},
    'otherwise_condition_type_inp_1': {'type': 'css', 'locator': '[data-test="otherwiseConditionType-1"] input'},
    'otherwise_condition_type_inp_2': {'type': 'css', 'locator': '[data-test="otherwiseConditionType-2"] input'},
    'next_condition_inp_1': {'type': 'css', 'locator': '[data-test="nextCondition-1"] input'},
    'next_condition_inp_2': {'type': 'css', 'locator': '[data-test="nextCondition-2"] input'},
    'otherwise_condition_inp_1': {'type': 'xpath', 'locator': '(//input[@placeholder="Условие"])[3]'},
    'otherwise_condition_inp_2': {'type': 'xpath', 'locator': '(//input[@placeholder="Условие"])[4]'},
    'next_condition_type_btn_1': {'type': 'css', 'locator': '[data-test="nextConditionType-1"] span'},
    'next_condition_type_btn_2': {'type': 'css', 'locator': '[data-test="nextConditionType-2"] span'},
    'otherwise_condition_type_btn_1': {'type': 'css', 'locator': '[data-test="otherwiseConditionType-1"] span'},
    'otherwise_condition_type_btn_2': {'type': 'css', 'locator': '[data-test="otherwiseConditionType-2"] span'},
    'next_condition_btn_1': {'type': 'css', 'locator': '[data-test="nextCondition-1"] span'},
    'next_condition_btn_2': {'type': 'css', 'locator': '[data-test="nextCondition-2"] span'},
    'otherwise_condition_btn_1': {'type': 'css', 'locator': '[data-test="otherwiseCondition-1"] span'},
    'otherwise_condition_btn_2': {'type': 'css', 'locator': '[data-test="otherwiseCondition-2"] span'},
    'set_btn': {'type': 'xpath', 'locator': '//div[contains(@data-test, "set")]'},
    'set_title': {'type': 'xpath', 'locator': '//div[contains(@data-test, "set")]/div[1]'},
    'set_descr': {'type': 'xpath', 'locator': '//div[contains(@data-test, "set")]/div[2]'},
    'except_btn': {'type': 'xpath', 'locator': '//div[contains(@data-test, "except")]'},
    'except_title': {'type': 'xpath', 'locator': '//div[contains(@data-test, "except")]/div[1]'},
    'except_descr': {'type': 'xpath', 'locator': '//div[contains(@data-test, "except")]/div[2]'},
    'condition_btn': {'type': 'xpath', 'locator': '//div[contains(text(), "Последовательное")]/..'},
    'condition_title': {'type': 'xpath', 'locator': '//div[contains(@data-test, "condition")]/div[1]'},
    'condition_descr': {'type': 'xpath', 'locator': '//div[contains(@data-test, "condition")]/div[2]'},
    'result_receiver_btn': {'type': 'xpath',
                            'locator': '//div[@class="menu"]//div[contains(text(), "Приёмник результатов")]'},
    'filter_rounding_btn': {'type': 'xpath', 'locator': '//div[@class="menu"]//div[contains(text(), "Округление")]'},
    'filter_monitoring_clipping_btn': {'type': 'xpath',
                                       'locator': '//div[@class="menu"]//div[contains(text(), "Отсечение мониторинга")]'},
    'filter_prices_counting_btn': {'type': 'xpath',
                                   'locator': '//div[@class="menu"]//div[contains(text(), "Подсчет количества")]'},
    'filter_search_family_product_btn': {'type': 'xpath',
                                         'locator': '//div[@class="menu"]//div[contains(text(), "Поиск товара")]'},
    'filter_adding_to_price_btn': {'type': 'xpath',
                                   'locator': '//div[@class="menu"]//div[contains(text(), "Прибавление")]'},
    'filter_complex_discounts_btn': {'type': 'xpath',
                                     'locator': '//div[@class="menu"]//div[contains(text(), "сложных скидок")]'},
    'filter_monitoring_btn': {'type': 'xpath',
                              'locator': '//div[@class="menu"]//div[contains(text(), "мониторингов")]'},
    'filter_balance_checking_btn': {'type': 'xpath',
                                    'locator': '//div[@class="menu"]//div[contains(text(), "остатоков")]'},
    'filter_percentile_btn': {'type': 'xpath', 'locator': '//div[@class="menu"]//div[contains(text(), "Процентиль")]'},
    'clear_next_condition_inp_btn_1': {'type': 'css',
                                       'locator': '[data-test=nextCondition-1] [data-test=clearableInput]'},
    'clear_next_condition_inp_btn_2': {'type': 'css',
                                       'locator': '[data-test=nextCondition-2] [data-test=clearableInput]'},
    'clear_otherwise_condition_inp_btn_1': {'type': 'css', 'locator': 'span[data-test="clearableInput"]'},
    'clear_otherwise_condition_inp_btn_2': {'type': 'css', 'locator': 'span[data-test="clearableInput"]'},
    'condition_name_inp': {'type': 'css', 'locator': '[data-test="conditionName"] input'},
    'comment_inp': {'type': 'css', 'locator': '[data-test="conditionComment"] textarea'},
    'sigma_inp': {'type': 'css', 'locator': '[data-test="argument-sigma"] input'},
    'second_condition_card': {'type': 'xpath', 'locator': '(//div[contains(@data-test, "rule-condition")])[2]'},
    'second_condition_card_name': {'type': 'xpath', 'locator': '(//div[contains(@data-test, "rule-condition")])[2]//h3'
                                                               '//span/span'},
    'condition_card_menu_btn': {'type': 'css', 'locator': '[data-test="contextMenu"]'},
    'visible_condition_card_menu_btn': {'type': 'xpath', 'locator': '(//div[@data-test="contextMenu"])[2]'},
    'replace_btn': {'type': 'css', 'locator': '.context-menu [role="button"]:nth-child(1)'},
    'condition_menu_delete_btn': {'type': 'css', 'locator': '.context-menu [role="button"]:nth-child(2)'},
    'visible_delete_btn': {'type': 'xpath', 'locator': '//div[not(contains(@class, "invisible"))]/div[@class="context-'
                                                       'menu rounded-lg"]/div[contains(text(), "Удалить")]'},
    'replace_to_adding': {'type': 'xpath', 'locator': '//input[@data-test="replaceOption-1104"]/../span[2]'},
    'replace_to_rounding': {'type': 'xpath', 'locator': '//input[@data-test="replaceOption-1101"]/../span[2]'},
    'replace_to_percentile': {'type': 'xpath', 'locator': '//input[@data-test="replaceOption-1103"]/../span[2]'},
    'condition_header': {'type': 'css', 'locator': '.conditions-building__header>:nth-child(2)>:nth-child(1)'},
    'rounding_subtitle': {'type': 'css', 'locator': '.rule-setup__subtitle'},
    'rounding_up': {'type': 'xpath', 'locator': '//input[@data-test="argument-priceRoundingDirection-up"]/../span[2]'},
    'rounding_down': {'type': 'xpath',
                      'locator': '//input[@data-test="argument-priceRoundingDirection-down"]/../span[2]'},
    'rounding_bit_depth_inp': {'type': 'css', 'locator': '[data-test="argument-priceRoundingBitDepth"] input'},
    'filter_menu': {'type': 'css', 'locator': '.search-filter__menu'},
    'tens_of_kopecks': {'type': 'css', 'locator': '.search-filter__menu [data-index="0"]>div>div'},
    'tens_of_rubles': {'type': 'css', 'locator': '.search-filter__menu [data-index="1"]>div>div'},
    'kopecks': {'type': 'css', 'locator': '.search-filter__menu [data-index="2"]>div>div'},
    'rubles': {'type': 'css', 'locator': '.search-filter__menu [data-index="3"]>div>div'},
    'percentile_inp': {'type': 'css', 'locator': '[data-test="argument-percentile"] input'},
    'prices_count_inp': {'type': 'css', 'locator': '[data-test="argument-pricesCountCondition"] input'},
    'prices_count_value_inp': {'type': 'css', 'locator': '[data-test="argument-pricesCountAmount"] input'},
    'more': {'type': 'css', 'locator': '.search-filter__menu [data-index="0"]>div>div'},
    'more_or_equal': {'type': 'css', 'locator': '.search-filter__menu [data-index="1"]>div>div'},
    'less': {'type': 'css', 'locator': '.search-filter__menu [data-index="2"]>div>div'},
    'less_or_equal': {'type': 'css', 'locator': '.search-filter__menu [data-index="3"]>div>div'},
    'equal': {'type': 'css', 'locator': '.search-filter__menu [data-index="4"]>div>div'},

    # 5th step
    'price_list_inp': {'type': 'css', 'locator': '[data-test="enterPriceListName"] input'},
    'price_list_label': {'type': 'css', 'locator': '[data-test="enterPriceListName"] label'},
    'priority_inp': {'type': 'css', 'locator': '[data-test="enterPriceListPriority"] input'},
    'priority_label': {'type': 'css', 'locator': '[data-test="enterPriceListPriority"] label'},
    'current_start_date_label': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(1) > div:nth-child(3) > '
                                                           'label:nth-child(1) span.radio__label'},
    'current_start_date_input': {'type': 'css', 'locator': '[data-test="choosePricePeriodCurrentStartDate"]'},
    'current_start_date_span': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(1) > div:nth-child(3) > '
                                                          'label:nth-child(1) span.radio__control'},
    'next_start_date_label': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(1) > div:nth-child(3) > '
                                                        'label:nth-child(2) span.radio__label'},
    'next_start_date_input': {'type': 'css', 'locator': '[data-test="choosePricePeriodNextStartDate"]'},
    'next_start_date_span': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(1) > div:nth-child(3) > '
                                                       'label:nth-child(2) span.radio__control'},
    'calculation_end_date_label': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(1) > div:nth-child(5) > '
                                                             'label:nth-child(1) span.radio__label'},
    'calculation_end_date_input': {'type': 'css', 'locator': '[data-test="choosePricePeriodEndCalculationDate"]'},
    'day_of_week_end_date_label': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(1) > div:nth-child(5) > '
                                                             'label:nth-child(2) span.radio__label'},
    'day_of_week_end_date_input': {'type': 'css', 'locator': '[data-test="choosePricePeriodEndDayOfWeek"]'},
    'calculation_end_date_span': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(1) > div:nth-child(5) > '
                                                            'label:nth-child(1) span.radio__control'},
    'day_of_week_end_date_span': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(1) > div:nth-child(5) > '
                                                            'label:nth-child(2) span.radio__control'},
    'period_end_day_label': {'type': 'css', 'locator': '[data-test="selectPricePeriodEndDay"] label'},
    'period_end_day_inp': {'type': 'css', 'locator': '[data-test="selectPricePeriodEndDay"]'},
    'period_end_day_open_btn': {'type': 'css', 'locator': '[data-test="selectPricePeriodEndDay"] span'},
    'period_days_search': {'type': 'css', 'locator': '[data-test="search"]'},
    'mon_item': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(1)'},
    'tue_item': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(2)'},
    'wed_item': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(3)'},
    'thu_item': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(4)'},
    'fri_item': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(5)'},
    'sat_item': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(6)'},
    'sun_item': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper > div:nth-child(7)'},
    'week_title': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(1) > div:nth-child(6) p'},
    'this_week_span': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(1) > div:nth-child(6) > label:'
                                                 'nth-of-type(1) .radio__control'},
    'this_week_label': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(1) > div:nth-child(6) > label:'
                                                  'nth-of-type(1) .radio__label'},
    'this_week_inp': {'type': 'css', 'locator': '[data-test="choosePricePeriodCurrentEndWeek"]'},
    'next_week_span': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(1) > div:nth-child(6) > label:'
                                                 'nth-of-type(2) .radio__control'},
    'next_week_label': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(1) > div:nth-child(6) > label:'
                                                  'nth-of-type(2) .radio__label'},
    'next_week_inp': {'type': 'css', 'locator': '[data-test="choosePricePeriodNextEndWeek"]'},
    'is_special_true_inp': {'type': 'css', 'locator': '[data-test="choosePriceListSpecialUseYes"]'},
    'is_special_false_inp': {'type': 'css', 'locator': '[data-test="choosePriceListSpecialUseNo"]'},
    'is_special_true_span': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(2) > div:nth-child(5) '
                                                       'label:nth-child(1) .radio__control'},
    'is_special_false_span': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(2) > div:nth-child(5) '
                                                        'label:nth-child(2) .radio__control'},
    'period_title': {'type': 'css', 'locator': '.calculator-setup > div:nth-child(1) > .rule-setup__title'},
    'period_start_subtitle': {'type': 'css', 'locator': '.calculator-setup > div:nth-child(1) >p:nth-child(2)'},
    'period_end_subtitle': {'type': 'css', 'locator': '.calculator-setup > div:nth-child(1) > p:nth-child(4)'},
    'price_list_title': {'type': 'css', 'locator': '.calculator-setup > div:nth-child(2) > .rule-setup__title'},
    'name_subtitle': {'type': 'css', 'locator': '.calculator-setup > div:nth-child(2) > div:nth-child(2)'},
    'settings_subtitle': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(2) div:nth-child(1) '
                                                    '.text-base-medium'},
    'is_special_subtitle': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(2) div:nth-child(2) '
                                                      '.text-base-medium'},
    'reason_title': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(3) .rule-setup__title'},
    'main_reason_subtitle': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(3) > div:nth-child(2)'},
    'additional_reason_subtitle': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(3) > div:nth-child(4)'},
    'promo_title': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(4) .rule-setup__title'},
    'main_promo_subtitle': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(4) > p:nth-child(2)'},
    'additional_promo_subtitle': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(4) > div:nth-child(4)'},
    'region_checkbox_inp': {'type': 'css', 'locator': '[data-test="checkPriceListRegionOption"]'},
    'locality_checkbox_inp': {'type': 'css', 'locator': '[data-test="checkPriceListLocalityOption"]'},
    'region_span': {'type': 'css',
                    'locator': '.rule-setup__block:nth-of-type(2) label:nth-child(1) .checkbox__control'},
    'region_label': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(2) label:nth-child(1) .checkbox__label'},
    'locality_span': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(2) label:nth-child(2) '
                                                '.checkbox__control'},
    'locality_label': {'type': 'css',
                       'locator': '.rule-setup__block:nth-of-type(2) label:nth-child(2) .checkbox__label'},
    'start_date_error_msg': {'type': 'css',
                             'locator': '.rule-setup__block:nth-of-type(1) div:nth-child(2) .error-message'},
    'end_date_error_msg': {'type': 'css',
                           'locator': '.rule-setup__block:nth-of-type(1) div:nth-child(4) .error-message'},
    'is_special_error_msg': {'type': 'css', 'locator': '.rule-setup__block:nth-of-type(2) .error-message'},
    'reason_open_btn': {'type': 'css', 'locator': 'div[data-test="selectMainPriceReason"] span'},
    'reason_inp': {'type': 'css', 'locator': 'div[data-test="selectMainPriceReason"] input'},
    'is_promo_yes': {'type': 'xpath', 'locator': '//input[@data-test="chooseMainPromotionYes"]/../span[1]'},
    'is_promo_no': {'type': 'xpath', 'locator': '//input[@data-test="chooseMainPromotionNo"]/../span[1]'},
    'filter_item': {'type': 'css', 'locator': '.search-filter__item'},
}
