
SHELF_PRICES = {
    # main shelf_prices page
    'first_tab': {'type': 'css', 'locator': '.versatile-header__filters .tab:nth-of-type(1)'},
    'second_tab': {'type': 'css', 'locator': '.versatile-header__filters .tab:nth-of-type(2)'},
    'no_data_txt': {'type': 'css', 'locator': '.no-data p'},
    'first_lvl_category_btn': {'type': 'css', 'locator': '.section:nth-of-type(1)>button'},
    'first_lvl_categories': {'type': 'css', 'locator': '.section-button__text'},
    'first_expanded_category_btn': {'type': 'css', 'locator': '[data-collapse="expanded"] button:nth-of-type(1)'},
    'analogue_group_header': {'type': 'css', 'locator': '.analogue-group .header>div:nth-child(1)'},
    'analogue_code_header': {'type': 'css', 'locator': '.analogue-group .header>div:nth-child(2)>:nth-child(1)'},
    'current_price_header': {'type': 'css', 'locator': '.analogue-group .header>div:nth-child(2)>:nth-child(2)'},
    'calculated_price_header': {'type': 'css', 'locator': '.analogue-group .header>div:nth-child(2)>:nth-child(3)'},
    'with_leftovers_header': {'type': 'css', 'locator': '.analogue-group .header>div:nth-child(2)>:nth-child(4)'},
    'first_analogue_card': {'type': 'css', 'locator': '.analogue-group>.analogue-card:nth-child(2)'},
    'analogue_card_category': {'type': 'css', 'locator': '.analogue-group>.analogue-card:nth-child(2)>div:nth-child(1)'},
    'analogue_card_name': {'type': 'css', 'locator': '.analogue-group>.analogue-card:nth-child(2)>a'},
    'go_to_analogue_btn': {'type': 'css', 'locator': '.analogue-group>.analogue-card:nth-child(2)>a>span'},
    'analogue_card_code': {'type': 'css', 'locator': '.analogue-group>.analogue-card:nth-child(2)>:nth-child(3)>'
                                                     ':nth-child(1)'},
    'analogue_card_current_price': {'type': 'css', 'locator': '.analogue-group>.analogue-card:nth-child(2)>'
                                                              ':nth-child(3)>:nth-child(2)'},
    'analogue_card_calculated_price': {'type': 'css', 'locator': '.analogue-group>.analogue-card:nth-child(2)>'
                                                                 ':nth-child(3)>:nth-child(3)'},
    'analogue_card_indicator': {'type': 'css', 'locator': '.indicator'},
    'analogue_card_stores': {'type': 'css', 'locator': '.analogue-group>.analogue-card:nth-child(2)>:nth-child(3)>'
                                                       ':nth-child(4)'},
    # second lvl shelf_prices page
    'table': {'type': 'css', 'locator': '.flex-table__body'},
    'first_row': {'type': 'css', 'locator': '.flex-table__body>div>div>:nth-child(1) .flex-table-row'},
    'region_title': {'type': 'css', 'locator': '[data-test="column-header-k1"]'},
    'current_price_title': {'type': 'css', 'locator': '[data-test="column-header-k2"]'},
    'calculated_price_title': {'type': 'css', 'locator': '[data-test="column-header-k3"]'},
    'kib_price_title': {'type': 'css', 'locator': '[data-test="column-header-k4"]'},
    'cost_price_title': {'type': 'css', 'locator': '[data-test="column-header-k5"]'},
    'purchase_price_title': {'type': 'css', 'locator': '[data-test="column-header-k6"]'},
    'twentieth_percentile_title': {'type': 'css', 'locator': '[data-test="column-header-k7"]'},
    'region_cell': {'type': 'css', 'locator': 'a[role=button] div.flex-table-cell:nth-child(1)'},
    'region_link': {'type': 'css', 'locator': 'a[role=button] div.flex-table-cell:nth-child(1)>div>a'},
    'current_price_cell': {'type': 'css', 'locator': 'a[role=button] div.flex-table-cell:nth-child(2)'},
    'calculated_price_cell': {'type': 'css', 'locator': 'a[role=button] div.flex-table-cell:nth-child(3)'},
    'kib_price_cell': {'type': 'css', 'locator': 'a[role=button] div.flex-table-cell:nth-child(4)'},
    'cost_price_cell': {'type': 'css', 'locator': 'a[role=button] div.flex-table-cell:nth-child(5)'},
    'purchase_price_cell': {'type': 'css', 'locator': 'a[role=button] div.flex-table-cell:nth-child(6)'},
    'percentile_cell': {'type': 'css', 'locator': 'a[role=button] div.flex-table-cell:nth-child(7)'},
    'analogue_name_in_header': {'type': 'css', 'locator': '.analogue-name'},
    'nav_breads': {'type': 'css', 'locator': 'nav.versatile-header__breads'},
    'base_breadcrumb': {'type': 'css', 'locator': '.versatile-header__breads li:nth-of-type(1)'},
    'second_breadcrumb': {'type': 'css', 'locator': '.versatile-header__breads li:nth-of-type(2)'},
    'third_breadcrumb': {'type': 'css', 'locator': '.versatile-header__breads li:nth-of-type(3)'},
    'fourth_breadcrumb': {'type': 'css', 'locator': '.versatile-header__breads li:nth-of-type(4)'},
    'sidepanel_current_price_title': {'type': 'css', 'locator': '.side-panel__head>div>div>:nth-child(1)'},
    'sidepanel_current_price_value': {'type': 'css', 'locator': '.side-panel__head>div>div>:nth-child(2)'},
    'sidepanel_calculated_price_title': {'type': 'css', 'locator': '.side-panel__head>div>:nth-child(2)>:nth-child(1)'},
    'sidepanel_calculated_price_value': {'type': 'css', 'locator': '.side-panel__head>div>:nth-child(2)>:nth-child(2)'},
    'region_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(1) h5'},
    'region_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(1) div'},
    'kib_price_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(2) h5'},
    'kib_price_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(2) div'},
    'percentile_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(3) h5'},
    'percentile_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(3) div'},
    'RTP_category': {'type': 'css', 'locator': '#toggle-a8b4fde2-b423-458b-a40d-bed6c4f6aebf'},
    'other_rtp': {'type': 'xpath', 'locator': '//button[contains(text(), "ПРОЧЕЕ_RRP")]'},
    'juul_port': {'type': 'xpath', 'locator': '//a[contains(text(), "Зарядный порт USB JUUL")]'},
    # 3rd lvl shelf_prices page
    'locality_title': {'type': 'css', 'locator': '[data-test="column-header-k1"]'},
    'regular_price_title': {'type': 'css', 'locator': '[data-test="column-header-k8"]'},
    'modal_competitor_price_title': {'type': 'css', 'locator': '[data-test="column-header-k9"]'},
    'average_competitor_price_title': {'type': 'css', 'locator': '[data-test="column-header-k10"]'},
    'locality_cell': {'type': 'css', 'locator': 'a[role=button] div.flex-table-cell:nth-child(1)'},
    'regular_price_cell': {'type': 'css', 'locator': 'a[role=button] div.flex-table-cell:nth-child(8)'},
    'modal_competitor_price_cell': {'type': 'css', 'locator': 'a[role=button] div.flex-table-cell:nth-child(9)'},
    'average_competitor_price_cell': {'type': 'css', 'locator': 'a[role=button] div.flex-table-cell:nth-child(10)'},
    'locality_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(2) h5'},
    'locality_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(2) div'},
    'reason_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(3) h5'},
    'reason_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(3) div'},
    'loc_kib_price_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(4) h5'},
    'loc_kib_price_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(4) div'},
    'cost_price_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(5) h5'},
    'cost_price_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(5) div'},
    'purchase_price_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(6) h5'},
    'purchase_price_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(6) div'},
    'loc_percentile_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(7) h5'},
    'loc_percentile_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(7) div'},
    'regular_price_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(8) h5'},
    'regular_price_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(8) div'},
    'modal_price_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(9) h5'},
    'modal_price_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(9) div'},
    'average_price_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(10) h5'},
    'average_price_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(10) div'},
    'mrc_label': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(11) h5'},
    'mrc_inp': {'type': 'css', 'locator': '.side-panel__content .side-panel-info-item:nth-child(11) div'},

}
