SHOPS = {

    'table': {'type': 'css', 'locator': '.vue-recycle-scroller__item-wrapper'},
    'nav_breads': {'type': 'css', 'locator': 'nav.versatile-header__breads'},

    # contestant section locators
    'store_region_title': {'type': 'css', 'locator': 'div[data-test="column-header-storeRegion"]'},
    'store_region_cell': {'type': 'css', 'locator': '[data-test="contestant-store-region"]'},
    'competitor_locality_cell': {'type': 'css', 'locator': '[data-test="contestant-locality"]'},
    'competitor_locality_title': {'type': 'css', 'locator': '[data-test="column-header-locality"]'},
    'competitor_department_title': {'type': 'css', 'locator': '[data-test="column-header-departament"]'},
    'competitor_department_cell': {'type': 'css', 'locator': '[data-test="contestant-departament"]'},
    'competitor_address_title': {'type': 'css', 'locator': 'div[data-test="column-header-address"]'},
    'competitor_address_cell': {'type': 'css', 'locator': '[data-test="contestant-address"]'},
    'competitor_name_cell': {'type': 'css', 'locator': '[data-test="contestant-name"]'},
    'competitor_name_title': {'type': 'css', 'locator': '[data-test="column-header-name"]'},
    'competitor_is_active_title': {'type': 'css', 'locator': 'div[data-test="column-header-isActive"]'},
    'competitor_is_active_cell': {'type': 'css', 'locator': '[data-test="contestant-is-active"]'},
    'competitor_distance_title': {'type': 'css', 'locator': 'div[data-test="column-header-distance"]'},
    'competitor_distance_cell': {'type': 'css', 'locator': '[data-test="contestant-distance"]'},
    'connection_guid_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(1) h5'},
    'connection_guid_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(1) div'},
    'store_guid_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(2) h5'},
    'store_guid_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(2) div'},
    'store_region_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(3) h5'},
    'store_region_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(3) div'},
    'locality_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(4) h5'},
    'locality_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(4) div'},
    'store_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(5) h5'},
    'store_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(5) div'},
    'competitor_address_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(6) h5'},
    'competitor_address_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(6) div'},
    'competitor_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(7) h5'},
    'competitor_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(7) div'},
    'is_active_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(8) h5'},
    'is_active_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(8) div'},
    'remoteness_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(9) h5'},
    'remoteness_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(9) div'},
    'latitude_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(10) > div:nth-child(1) h5'},
    'latitude_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(10) > div:nth-child(1) div'},
    'longitude_label': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(10) > div:nth-child(2) h5'},
    'longitude_value': {'type': 'css', 'locator': '.side-panel__content > div > div:nth-child(10) > div:nth-child(2) div'},

    # divisions section
    'division_code_title': {'type': 'css', 'locator': '[data-test="column-header-departmentCode"] div'},
    'division_code_cell': {'type': 'css', 'locator': '[data-test="item-id"]'},
    'division_region_title': {'type': 'css', 'locator': '[data-test="column-header-region"] div'},
    'division_region_cell': {'type': 'css', 'locator': '[data-test="item-region-name"]'},
    'division_locality_title': {'type': 'css', 'locator': '[data-test="column-header-locality"] div'},
    'division_locality_cell': {'type': 'css', 'locator': '[data-test="item-city-name"]'},
    'subdivision_title': {'type': 'css', 'locator': '[data-test="column-header-subdivision"] div'},
    'subdivision_cell': {'type': 'css', 'locator': '[data-test="item-store-address"]'},
    'connection_bristol_title': {'type': 'css', 'locator': '[data-test="column-header-connectionBristol"] div'},
    'connection_bristol_cell': {'type': 'css', 'locator': '.flex-table__body .flex-table-cell:nth-of-type(5)'},
    'connection_kib_title': {'type': 'css', 'locator': '[data-test="column-header-connectionKib"] div'},
    # 'connection_kib_cell': {'type': 'css', 'locator': '[data-test="item-connection-kib"]'},
    'connection_kib_cell': {'type': 'css', 'locator': '.flex-table__body .flex-table-cell:nth-of-type(6)'},
    'segment_title': {'type': 'css', 'locator': '[data-test="column-header-segment"] div'},
    'segment_cell': {'type': 'css', 'locator': '[data-test="item-segment"]'},
    'store_status_title': {'type': 'css', 'locator': '[data-test="column-header-storeStatus"] div'},
    'store_status_cell': {'type': 'css', 'locator': '[data-test="item-store-status"]'},
    'region_label': {'type': 'css', 'locator': '[data-test="region-name"] h5'},
    'region_inp': {'type': 'css', 'locator': '[data-test="region-name"] div'},
    'division_locality_label': {'type': 'css', 'locator': '[data-test="city-name"] h5'},
    'division_locality_inp': {'type': 'css', 'locator': '[data-test="city-name"] div'},
    'city_code_label': {'type': 'css', 'locator': '[data-test="city-id"] h5'},
    'city_code_inp': {'type': 'css', 'locator': '[data-test="city-id"] div'},
    'organization_code_label': {'type': 'css', 'locator': '[data-test="organization-id"] h5'},
    'organization_code_inp': {'type': 'css', 'locator': '[data-test="organization-id"] div'},
    'division_code_label': {'type': 'css', 'locator': '[data-test="division-id"] h5'},
    'division_code_inp': {'type': 'css', 'locator': '[data-test="division-id"] div'},
    'region_code_label': {'type': 'css', 'locator': '[data-test="region-id"] h5'},
    'region_code_inp': {'type': 'css', 'locator': '[data-test="region-id"] div'},
    'subdivision_code_label': {'type': 'css', 'locator': '[data-test="department-id"] h5'},
    'subdivision_code_inp': {'type': 'css', 'locator': '[data-test="department-id"] div'},
    'subdivision_label': {'type': 'css', 'locator': '[data-test="store-address"] h5'},
    'subdivision_inp': {'type': 'css', 'locator': '[data-test="store-address"] div'},
    'subdivision_guid_label': {'type': 'css', 'locator': '[data-test="store-organization-structure-id"] h5'},
    'subdivision_guid_inp': {'type': 'css', 'locator': '[data-test="store-organization-structure-id"] div'},
    'bristol_connection_label': {'type': 'css', 'locator': '[data-test="connection-bristol"] h5'},
    'bristol_connection_inp': {'type': 'css', 'locator': '[data-test="connection-bristol"] div'},
    'kib_territory_code_label': {'type': 'css', 'locator': '[data-test="kib-code"] h5'},
    'kib_territory_code_inp': {'type': 'css', 'locator': '[data-test="kib-code"] div'},
    'kib_connection_label': {'type': 'css', 'locator': '[data-test="connection-kib"] h5'},
    'kib_connection_inp': {'type': 'css', 'locator': '[data-test="connection-kib"] div'},
    'kib_region_label': {'type': 'css', 'locator': '[data-test="kib-region"] h5'},
    'kib_region_inp': {'type': 'css', 'locator': '[data-test="kib-region"] div'},
    'shop_guid_label': {'type': 'css', 'locator': '[data-test="store-warehouse-structure-id"] h5'},
    'shop_guid_inp': {'type': 'css', 'locator': '[data-test="store-warehouse-structure-id"] div'},
    'segment_label': {'type': 'css', 'locator': '[data-test="segment"] h5'},
    'segment_inp': {'type': 'css', 'locator': '[data-test="segment"] div'},
    'shop_status_label': {'type': 'css', 'locator': '[data-test="storeStatusText"] h5'},
    'shop_status_inp': {'type': 'css', 'locator': '[data-test="storeStatusText"] div'},
    'first_sale_date_label': {'type': 'css', 'locator': '[data-test="store-first-sale-date"] h5'},
    'first_sale_date_inp': {'type': 'css', 'locator': '[data-test="store-first-sale-date"] div'},
    'kib_latitude_label': {'type': 'css', 'locator': '[data-test="store-latitude"] h5'},
    'kib_latitude_inp': {'type': 'css', 'locator': '[data-test="store-latitude"] div'},
    'kib_longitude_label': {'type': 'css', 'locator': '[data-test="store-longitude"] h5'},
    'kib_longitude_inp': {'type': 'css', 'locator': '[data-test="store-longitude"] div'},
}
