TASK_TEMPLATE = {
    'header2': {'type': 'css', 'locator': 'h2'},
    'header1': {'type': 'css', 'locator': 'h1.versatile-header__title'},
    # template's adding
    'add_template_btn': {'type': 'css', 'locator': '.versatile-header__actions button'},
    'template_name_inp': {'type': 'css', 'locator': '.side-panel__content>div:nth-child(1) input'},
    'rule_inp': {'type': 'css', 'locator': '.side-panel__content>div:nth-child(2) input'},
    'responsible_inp': {'type': 'css', 'locator': '.side-panel__content>div:nth-child(3) input'},
    'time_inp': {'type': 'css', 'locator': '.side-panel__content>div:nth-child(4) input'},
    # template's card
    'card': {'type': 'css', 'locator': '.card-wrap'},
    'card_name': {'type': 'css', 'locator': '.card-wrap h3'},
    'context_menu_btn': {'type': 'css', 'locator': '.card-wrap [data-test="toggle"] > div'},
    'card_id': {'type': 'css', 'locator': '.card-wrap > div:nth-child(2)'},
    'card_schedule': {'type': 'css', 'locator': '.card-wrap > div:nth-child(4)'},
    'card_responsible': {'type': 'css', 'locator': '.card-wrap>div:nth-child(3)>:nth-child(1)>:nth-child(1)'},
    'card_responsible_name': {'type': 'css', 'locator': '.card-wrap>div:nth-child(3)>:nth-child(1)>:nth-child(2)'},
    'card_author': {'type': 'css', 'locator': '.card-wrap>div:nth-child(3)>:nth-child(2)>:nth-child(1)'},
    'card_author_name': {'type': 'css', 'locator': '.card-wrap>div:nth-child(3)>:nth-child(2)>:nth-child(2)'},
    'card_date': {'type': 'css', 'locator': '.card-wrap>div:nth-child(3)>:nth-child(2)>:nth-child(1)'},
    'card_date_name': {'type': 'css', 'locator': '.card-wrap>div:nth-child(3)>:nth-child(2)>:nth-child(2)'},
    'context_menu_more_btn': {'type': 'css', 'locator': '.context-menu>div:nth-child(1)'},
    'context_menu_edit_btn': {'type': 'css', 'locator': '.context-menu>div:nth-child(2)'},
    'context_menu_delete_btn': {'type': 'css', 'locator': '.context-menu>div:nth-child(3)'},
    # view template
    'template_name_header': {'type': 'css', 'locator': '.side-panel__content>div:nth-child(1) h5'},
    'template_name_value': {'type': 'css', 'locator': '.side-panel__content>div:nth-child(1) div'},
    'rule_header': {'type': 'css', 'locator': '.side-panel__content>div:nth-child(2) h5'},
    'rule_value': {'type': 'css', 'locator': '.side-panel__content>div:nth-child(2) div'},
    'responsible_header': {'type': 'css', 'locator': '.side-panel__content>div:nth-child(3) h5'},
    'responsible_value': {'type': 'css', 'locator': '.side-panel__content>div:nth-child(3) div'},
    'time_header': {'type': 'css', 'locator': '.side-panel__content>div:nth-child(3) h5'},
    'time_value': {'type': 'css', 'locator': '.side-panel__content>div:nth-child(3) div'},
}
