USERS = {
    'add_user_btn': {'type': 'css', 'locator': 'button[data-test="add"]'},
    'lastname_inp': {'type': 'css', 'locator': 'div[data-test="lastName"] input'},
    'firstname_inp': {'type': 'css', 'locator': 'div[data-test="firstName"] input'},
    'surname_inp': {'type': 'css', 'locator': 'div[data-test="surName"] input'},
    'account_inp': {'type': 'css', 'locator': 'div[data-test="account"] input'},
    'role_inp': {'type': 'css', 'locator': 'div[data-test="role"] input'},
    'role_dropdown_btn': {'type': 'css', 'locator': 'div[data-test="role"] span'},
    'nsi_admin_role': {'type': 'xpath', 'locator': '//div[text()[contains(.,"Администратор НСИ")]]'},
    'system_admin_role': {'type': 'xpath', 'locator': '//div[text()[contains(.,"Администратор системы")]]'},
    'marketing_manager_role': {'type': 'xpath', 'locator': '//div[text()[contains(.,"Менеджер отдела маркетинга")]]'},
    'price_setting_manager_role': {'type': 'xpath', 'locator': '//div[text()[contains(.,"установки цен")]]'},
    'price_manager_role': {'type': 'xpath', 'locator': '//div[text()[contains(.,"ценообразования")]]'},
    'category_manager_role': {'type': 'xpath', 'locator': '//div[text()[contains(.,"категорийного")]]'},
    'department_inp': {'type': 'css', 'locator': 'div[data-test="department"] input'},
    'hr_department': {'type': 'xpath', 'locator': '(//div[@class="search-filter__menu-item"])[1]'},
    'design_department': {'type': 'xpath', 'locator': '(//div[@class="search-filter__menu-item"])[2]'},
    'marketing_department': {'type': 'xpath', 'locator': '(//div[@class="search-filter__menu-item"])[3]'},
    'management_department': {'type': 'xpath', 'locator': '(//div[@class="search-filter__menu-item"])[4]'},
    'dev_department': {'type': 'css', 'locator': '[data-index="4"]'},
    'category_input': {'type': 'css', 'locator': 'div[data-test="category"] input'},
    'category_dropdown_btn': {'type': 'css', 'locator': 'div[data-test="category"] span'},
    'select_all_checkbox': {'type': 'css', 'locator': 'input[data-test="select-all"]'},
    'first_category_checkbox': {'type': 'xpath', 'locator': '(//input[@class="checkbox__input"])[2]'},
    'second_category_checkbox': {'type': 'xpath', 'locator': '(//input[@class="checkbox__input"])[3]'},
    'third_category_checkbox': {'type': 'xpath', 'locator': '(//input[@class="checkbox__input"])[4]'},
    'total_users_tab': {'type': 'css', 'locator': '.versatile-header__tabs .tab:nth-child(1)'},
    'activated_users_tab': {'type': 'css', 'locator': '.versatile-header__tabs .tab:nth-child(2)'},
    'not_activated_users_tab': {'type': 'css', 'locator': '.versatile-header__tabs .tab:nth-child(3)'},
    'banned_users_tab': {'type': 'css', 'locator': '.versatile-header__tabs .tab:nth-child(4)'},
    'username_title': {'type': 'css', 'locator': 'div[data-test="column-header-user"]'},
    'username_cell': {'type': 'xpath', 'locator': '//a[@data-test="item-id-0"]/div[1]/div'},
    'account_title': {'type': 'css', 'locator': 'div[data-test="column-header-account"]'},
    'account_cell': {'type': 'xpath', 'locator': '//a[@data-test="item-id-0"]/div[2]/div'},
    'role_title': {'type': 'css', 'locator': 'div[data-test="column-header-role"]'},
    'role_cell': {'type': 'xpath', 'locator': '//a[@data-test="item-id-0"]/div[3]/div'},
    'status_title': {'type': 'css', 'locator': 'div[data-test="column-header-status"]'},
    'status_cell': {'type': 'xpath', 'locator': '//a[@data-test="item-id-0"]/div[4]/div/div'},
    'side_panel_user_info': {'type': 'css', 'locator': '.user-info'},
    'side_panel_user_status': {'type': 'css', 'locator': '.side-panel__content .user__status'},
    'unlock_popup': {'type': 'css', 'locator': '.modal-content'},
    'unlock_popup_header': {'type': 'css', 'locator': '.modal-content h5'},
    'unlock_popup_body': {'type': 'css', 'locator': '.modal-body div'},
    'confirm_unlock_btn': {'type': 'css', 'locator': 'button[data-test="confirm"]'},
    'cancel_unlock_btn': {'type': 'css', 'locator': 'button[data-test="close"]'},
    'block_user_btn': {'type': 'css', 'locator': 'button[data-test="block"]'},
    'unblock_user_btn': {'type': 'css', 'locator': 'button[data-test="unblock"]'},
    'visible_username_cell': {'type': 'css', 'locator': 'div:not([style="transform: translateY(-9999px) translateX(0px)'
                                                        ';"])>a>div:nth-child(1) [data-test="item-full-name"]'},
    'visible_account_cell': {'type': 'css', 'locator': 'div:not([style="transform: translateY(-9999px) translateX(0px)'
                                                       ';"])>a>div:nth-child(2) [data-test="item-full-name"]'},
    'visible_role_cell': {'type': 'css', 'locator': 'div:not([style="transform: translateY(-9999px) translateX(0px);"]'
                                                    ')>a>div:nth-child(3) [data-test="item-full-name"]'},
    'visible_status_cell': {'type': 'css', 'locator': 'div:not([style="transform: translateY(-9999px) translateX(0px);'
                                                      '"])>a  .user__status'},
    'visible_row': {'type': 'css', 'locator': 'div:not([style="transform: translateY(-9999px) translateX(0px);"])>a.'
                                              'flex-table-row'},
    'filter_dev_department': {'type': 'xpath', 'locator': '//span[text()[contains(.,"Отдел разработки")]]'},
    'filter_admin_nsi': {'type': 'xpath', 'locator': '//label/span[text()[contains(.,"НСИ")]]'},
    'sp_id': {'type': 'css', 'locator': '.side-panel__head>div:nth-of-type(1)'},
    'sp_author': {'type': 'css', 'locator': '.side-panel__head>div:nth-of-type(2)'},
    'user_header': {'type': 'css', 'locator': '.side-panel__content>div:nth-of-type(1) h5'},
    'email_header': {'type': 'css', 'locator': '.side-panel__content>div:nth-of-type(2) h5'},
    'role_header': {'type': 'css', 'locator': '.side-panel__content>div:nth-of-type(3) h5'},
    'department_header': {'type': 'css', 'locator': '.side-panel__content>div:nth-of-type(4) h5'},
    'status_header': {'type': 'css', 'locator': '.side-panel__content>div:nth-of-type(5) h5'},
    'user_value': {'type': 'css', 'locator': '.side-panel__content>div:nth-of-type(1) div'},
    'email_value': {'type': 'css', 'locator': '.side-panel__content>div:nth-of-type(2) div'},
    'role_value': {'type': 'css', 'locator': '.side-panel__content>div:nth-of-type(3) div'},
    'department_value': {'type': 'css', 'locator': '.side-panel__content>div:nth-of-type(4) div'},
    'status_value': {'type': 'css', 'locator': '.side-panel__content>div:nth-of-type(5) div'},
}
